export const CUSTOM_QUESTIONS_RO = [
{
  category: 9, // Cunostinte generale
  type: "multiple",
  difficulty: "easy",
  question: "Care este capitala Frantei?",
  correct_answer: "Paris",
  incorrect_answers: ["Londra", "Berlin", "Madrid"],
},
{
  category: 11, // Filme
  type: "multiple",
  difficulty: "medium",
  question: "Cine a regizat filmul 'Inception'?",
  correct_answer: "Christopher Nolan",
  incorrect_answers: ["Steven Spielberg", "Quentin Tarantino", "Martin Scorsese"],
},
// --- CUNOSTINTE GENERALE (BATCH 1) ---
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce animal este cunoscut ca 'Corabia desertului'?",
  correct_answer: "Camila",
  incorrect_answers: ["Cal", "Elefant", "Zebra"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cate zile are un an bisect?",
  correct_answer: "366",
  incorrect_answers: ["365", "364", "360"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste zeul grec al razboiului?",
  correct_answer: "Ares",
  incorrect_answers: ["Zeus", "Apollo", "Hermes"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce tara a oferit Statuia Libertatii Statelor Unite?",
  correct_answer: "Franta",
  incorrect_answers: ["Regatul Unit", "Spania", "Italia"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Care este cea mai rara grupa de sange?",
  correct_answer: "AB negativ",
  incorrect_answers: ["O pozitiv", "B negativ", "A pozitiv"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este cel mai mare ocean din lume?",
  correct_answer: "Oceanul Pacific",
  incorrect_answers: ["Oceanul Atlantic", "Oceanul Indian", "Oceanul Arctic"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce element chimic are simbolul 'K'?",
  correct_answer: "Potasiu",
  incorrect_answers: ["Kripton", "Keviniu", "Kalphon"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cine a pictat Mona Lisa?",
  correct_answer: "Leonardo da Vinci",
  incorrect_answers: ["Pablo Picasso", "Vincent van Gogh", "Michelangelo"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Care planeta are cei mai multi sateliti naturali?",
  correct_answer: "Saturn",
  incorrect_answers: ["Jupiter", "Uranus", "Neptun"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste frica de paianjeni?",
  correct_answer: "Arahnofobie",
  incorrect_answers: ["Acrofobie", "Claustrofobie", "Hidrofobie"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce fruct este asociat cu Isaac Newton?",
  correct_answer: "Mar",
  incorrect_answers: ["Para", "Portocala", "Banana"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce companie detine Bugatti, Lamborghini si Audi?",
  correct_answer: "Volkswagen",
  incorrect_answers: ["Toyota", "General Motors", "Ford"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este ingredientul principal din guacamole?",
  correct_answer: "Avocado",
  incorrect_answers: ["Rosie", "Ceapa", "Ardei"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cate inimi are o caracatita?",
  correct_answer: "3",
  incorrect_answers: ["1", "2", "4"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "In ce an a cazut Zidul Berlinului?",
  correct_answer: "1989",
  incorrect_answers: ["1987", "1991", "1990"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce inseamna prescurtarea 'www' intr-un browser web?",
  correct_answer: "World Wide Web",
  incorrect_answers: ["World Web Wide", "Wide World Web", "Web World Wide"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce fizician celebru a scris 'Scurta istorie a timpului'?",
  correct_answer: "Stephen Hawking",
  incorrect_answers: ["Albert Einstein", "Isaac Newton", "Niels Bohr"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Care este cel mai mic os din corpul uman?",
  correct_answer: "Scarita (osul urechii)",
  incorrect_answers: ["Falange", "Femur", "Tibia"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce litera urmeaza dupa 'F' in alfabet?",
  correct_answer: "G",
  incorrect_answers: ["E", "H", "I"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este cea mai dura substanta naturala de pe Pamant?",
  correct_answer: "Diamant",
  incorrect_answers: ["Aur", "Fier", "Platina"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce personaj Disney este un elefant zburator?",
  correct_answer: "Dumbo",
  incorrect_answers: ["Bambi", "Simba", "Pluto"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce oras este cunoscut sub numele de 'Marele Mar'?",
  correct_answer: "New York",
  incorrect_answers: ["Los Angeles", "Chicago", "Miami"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Ce element are numarul atomic 1?",
  correct_answer: "Hidrogen",
  incorrect_answers: ["Heliu", "Oxigen", "Carbon"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce culoare are un safir?",
  correct_answer: "Albastru",
  incorrect_answers: ["Rosu", "Verde", "Galben"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce tara a inventat pizza?",
  correct_answer: "Italia",
  incorrect_answers: ["SUA", "Franta", "China"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "In ce an a pasit primul om pe Luna?",
  correct_answer: "1969",
  incorrect_answers: ["1965", "1972", "1959"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cate picioare are un paianjen?",
  correct_answer: "8",
  incorrect_answers: ["6", "4", "10"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este floarea nationala a Japoniei?",
  correct_answer: "Floarea de cires",
  incorrect_answers: ["Trandafir", "Crin", "Lalea"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a scris romanul '1984'?",
  correct_answer: "George Orwell",
  incorrect_answers: ["Aldous Huxley", "Ernest Hemingway", "F. Scott Fitzgerald"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste forma inghetata a apei?",
  correct_answer: "Gheata",
  incorrect_answers: ["Abur", "Lichid", "Gaz"],
},
// --- CUNOSTINTE GENERALE (BATCH 2 - EXTINS) ---
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce limba are cei mai multi vorbitori nativi din lume?",
  correct_answer: "Mandarina",
  incorrect_answers: ["Engleza", "Spaniola", "Hindi"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este culoarea principala a logo-ului Netflix?",
  correct_answer: "Rosu",
  incorrect_answers: ["Albastru", "Verde", "Negru"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a fost prima femeie care a castigat un premiu Nobel?",
  correct_answer: "Marie Curie",
  incorrect_answers: ["Maica Tereza", "Jane Addams", "Rosalind Franklin"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce brand foloseste sloganul 'Just Do It'?",
  correct_answer: "Nike",
  incorrect_answers: ["Adidas", "Puma", "Reebok"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce pasare este cunoscuta pentru imitarea vocii umane?",
  correct_answer: "Papagal",
  incorrect_answers: ["Vultur", "Bufnita", "Pinguin"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este cel mai inalt mamifer din lume?",
  correct_answer: "Girafa",
  incorrect_answers: ["Elefant", "Balena albastra", "Cal"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Ce piesa de sah se poate misca doar pe diagonala?",
  correct_answer: "Nebun",
  incorrect_answers: ["Tura", "Cal", "Pion"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cate laturi are un triunghi?",
  correct_answer: "3",
  incorrect_answers: ["4", "5", "2"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este cea mai fierbinte planeta din sistemul nostru solar?",
  correct_answer: "Venus",
  incorrect_answers: ["Mercur", "Marte", "Jupiter"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste jucaria cowboy din 'Toy Story'?",
  correct_answer: "Woody",
  incorrect_answers: ["Buzz", "Andy", "Jessie"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "In ce an a aparut filmul Titanic?",
  correct_answer: "1997",
  incorrect_answers: ["1995", "1999", "2000"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce tara produce cea mai multa cafea din lume?",
  correct_answer: "Brazilia",
  incorrect_answers: ["Columbia", "Vietnam", "Etiopia"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este opusul cuvantului 'cald'?",
  correct_answer: "Rece",
  incorrect_answers: ["Caldut", "Tepos", "Picant"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a fondat Microsoft?",
  correct_answer: "Bill Gates",
  incorrect_answers: ["Steve Jobs", "Elon Musk", "Mark Zuckerberg"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este moneda Regatului Unit?",
  correct_answer: "Lira sterlina",
  incorrect_answers: ["Euro", "Dolar", "Yen"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce animal este simbolul WWF?",
  correct_answer: "Panda",
  incorrect_answers: ["Tigru", "Leu", "Urs"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cate stele sunt pe steagul Chinei?",
  correct_answer: "5",
  incorrect_answers: ["4", "6", "1"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce organ pompeaza sangele in corpul uman?",
  correct_answer: "Inima",
  incorrect_answers: ["Creierul", "Plamanii", "Ficatul"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este culoarea principala a unei banane?",
  correct_answer: "Galben",
  incorrect_answers: ["Rosu", "Verde", "Albastru"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce vas celebru s-a scufundat in 1912?",
  correct_answer: "Titanic",
  incorrect_answers: ["Lusitania", "Olympic", "Britannic"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Ce gaz reprezinta cea mai mare parte din atmosfera Pamantului?",
  correct_answer: "Azot",
  incorrect_answers: ["Oxigen", "Dioxid de carbon", "Hidrogen"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce produc albinele?",
  correct_answer: "Miere",
  incorrect_answers: ["Lapte", "Matase", "Lana"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Cine este autorul seriei 'Harry Potter'?",
  correct_answer: "J.K. Rowling",
  incorrect_answers: ["J.R.R. Tolkien", "George R.R. Martin", "Stephen King"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Ce reprezinta litera 'O' in codul Morse?",
  correct_answer: "---",
  incorrect_answers: ["...", ".-", "-.-"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce tara are cea mai mare populatie?",
  correct_answer: "India",
  incorrect_answers: ["China", "SUA", "Rusia"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce anotimp urmeaza dupa vara?",
  correct_answer: "Toamna",
  incorrect_answers: ["Iarna", "Primavara", "Muson"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce inseamna litera 'E' din 'Email'?",
  correct_answer: "Electronic",
  incorrect_answers: ["Electric", "Motor", "Usor"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Ce artist si-a taiat propria ureche?",
  correct_answer: "Vincent van Gogh",
  incorrect_answers: ["Pablo Picasso", "Claude Monet", "Salvador Dali"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este cel mai rapid animal de uscat?",
  correct_answer: "Ghepard",
  incorrect_answers: ["Leu", "Cal", "Tigru"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Cati jucatori sunt intr-o echipa standard de fotbal?",
  correct_answer: "11",
  incorrect_answers: ["10", "12", "9"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Care este capitala Canadei?",
  correct_answer: "Ottawa",
  incorrect_answers: ["Toronto", "Montreal", "Vancouver"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce personaj din basme a dormit 100 de ani?",
  correct_answer: "Frumoasa din padurea adormita",
  incorrect_answers: ["Cenusareasa", "Alba ca Zapada", "Rapunzel"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce producator auto are un cal in logo?",
  correct_answer: "Ferrari",
  incorrect_answers: ["Lamborghini", "Audi", "BMW"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a fost primul om care a pasit pe Luna?",
  correct_answer: "Neil Armstrong",
  incorrect_answers: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este cel mai mare organ intern din corpul uman?",
  correct_answer: "Ficatul",
  incorrect_answers: ["Inima", "Plamanii", "Stomacul"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce fel de mancare este Penne?",
  correct_answer: "Paste",
  incorrect_answers: ["Paine", "Branza", "Carne"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce tara este faimoasa pentru lalele si mori de vant?",
  correct_answer: "Olanda",
  incorrect_answers: ["Germania", "Elvetia", "Belgia"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Care este simbolul chimic pentru aur?",
  correct_answer: "Au",
  incorrect_answers: ["Ag", "Go", "Gd"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cate ore are o zi?",
  correct_answer: "24",
  incorrect_answers: ["12", "48", "36"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Cine a pictat tavanul Capelei Sixtine?",
  correct_answer: "Michelangelo",
  incorrect_answers: ["Leonardo da Vinci", "Raphael", "Donatello"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Ce razboi a fost purtat intre regiunile de Nord si Sud ale Statelor Unite?",
  correct_answer: "Razboiul Civil",
  incorrect_answers: ["Razboiul de Independenta", "Primul Razboi Mondial", "Razboiul din Vietnam"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este cea mai mare reptila vie?",
  correct_answer: "Crocodilul de apa sarata",
  incorrect_answers: ["Dragonul de Komodo", "Pitonu", "Aligatorul"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste orasul fictiv in care locuieste Batman?",
  correct_answer: "Gotham City",
  incorrect_answers: ["Metropolis", "Star City", "Central City"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cate dungi sunt pe steagul SUA?",
  correct_answer: "13",
  incorrect_answers: ["50", "10", "12"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce bautura racoritoare a fost initial verde?",
  correct_answer: "Niciuna (este un mit, dar este asociat des cu Mountain Dew)",
  incorrect_answers: ["Coca Cola", "Pepsi", "Sprite"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este cea mai dura roca?",
  correct_answer: "Diamant",
  incorrect_answers: ["Granit", "Marmura", "Cuart"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este ingredientul principal din ciocolata?",
  correct_answer: "Cacao",
  incorrect_answers: ["Lapte", "Zahar", "Vanilie"],
},
// --- FILME (BATCH 1 - MIX) ---
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In ce film apare un personaj numit Jack Sparrow?",
  correct_answer: "Pirates of the Caribbean",
  incorrect_answers: ["Harry Potter", "Lord of the Rings", "Indiana Jones"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In 'The Matrix', ce pastila ia Neo?",
  correct_answer: "Rosie",
  incorrect_answers: ["Albastra", "Verde", "Galbena"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cine l-a interpretat pe Iron Man in universul cinematografic Marvel?",
  correct_answer: "Robert Downey Jr.",
  incorrect_answers: ["Chris Evans", "Chris Hemsworth", "Mark Ruffalo"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Ce film a castigat Oscarul pentru Cel mai bun film in 1994?",
  correct_answer: "Schindler's List",
  incorrect_answers: ["Pulp Fiction", "Forrest Gump", "The Shawshank Redemption"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste regatul din 'Frozen'?",
  correct_answer: "Arendelle",
  incorrect_answers: ["Genovia", "Aldovia", "Florin"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce dinozaur este antagonistul principal in 'Jurassic Park'?",
  correct_answer: "T-Rex",
  incorrect_answers: ["Velociraptor", "Triceratops", "Brachiosaurus"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cine a regizat filmul 'Avatar'?",
  correct_answer: "James Cameron",
  incorrect_answers: ["Steven Spielberg", "George Lucas", "Ridley Scott"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "In 'Pulp Fiction', cum se numeste un 'Quarter Pounder with Cheese' in Paris?",
  correct_answer: "Royale with Cheese",
  incorrect_answers: ["Le Big Mac", "French Burger", "Cheese Royale"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce fel de animal este Baloo in 'The Jungle Book'?",
  correct_answer: "Urs",
  incorrect_answers: ["Tigru", "Lup", "Pantera"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce actor a jucat Joker-ul in 'The Dark Knight'?",
  correct_answer: "Heath Ledger",
  incorrect_answers: ["Joaquin Phoenix", "Jared Leto", "Jack Nicholson"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cine locuieste intr-un ananas sub mare?",
  correct_answer: "SpongeBob SquarePants",
  incorrect_answers: ["Patrick Star", "Squidward", "Mr. Krabs"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cum se numeste computerul din '2001: A Space Odyssey'?",
  correct_answer: "HAL 9000",
  incorrect_answers: ["Skynet", "Jarvis", "Deep Blue"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Din ce film este citatul 'Here's looking at you, kid'?",
  correct_answer: "Casablanca",
  incorrect_answers: ["Gone with the Wind", "Citizen Kane", "The Godfather"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In 'Harry Potter', cum se numeste bufnita lui Harry?",
  correct_answer: "Hedwig",
  incorrect_answers: ["Scabbers", "Crookshanks", "Fang"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cine a jucat rolul lui Jack Dawson in 'Titanic'?",
  correct_answer: "Leonardo DiCaprio",
  incorrect_answers: ["Brad Pitt", "Matt Damon", "Johnny Depp"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Care a fost primul film lansat in Marvel Cinematic Universe?",
  correct_answer: "Iron Man",
  incorrect_answers: ["The Incredible Hulk", "Captain America", "Thor"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste capcaunul din 'Shrek'?",
  correct_answer: "Shrek",
  incorrect_answers: ["Donkey", "Fiona", "Farquaad"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In 'Star Wars', cine este tatal lui Luke Skywalker?",
  correct_answer: "Darth Vader",
  incorrect_answers: ["Obi-Wan Kenobi", "Palpatine", "Yoda"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Ce film este plasat in tara fictiva Wakanda?",
  correct_answer: "Black Panther",
  incorrect_answers: ["Coming to America", "District 9", "Hotel Rwanda"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce supererou este cunoscut ca 'Omul de otel'?",
  correct_answer: "Superman",
  incorrect_answers: ["Batman", "Iron Man", "Thor"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce actor si-a facut faimoase cascadoriile singur in 'Mission: Impossible'?",
  correct_answer: "Tom Cruise",
  incorrect_answers: ["Keanu Reeves", "Daniel Craig", "Jason Statham"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cum se numeste sania din 'Citizen Kane'?",
  correct_answer: "Rosebud",
  incorrect_answers: ["Snowbird", "Thunder", "Lightning"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In 'Finding Nemo', ce fel de peste este Nemo?",
  correct_answer: "Peste clovn",
  incorrect_answers: ["Peste auriu", "Rechin", "Peste balon"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce film are un parc tematic cu dinozauri clonati?",
  correct_answer: "Jurassic Park",
  incorrect_answers: ["King Kong", "Godzilla", "Planet of the Apes"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'Psycho'?",
  correct_answer: "Alfred Hitchcock",
  incorrect_answers: ["Stanley Kubrick", "Francis Ford Coppola", "Martin Scorsese"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce personaj spune 'I am Groot'?",
  correct_answer: "Groot",
  incorrect_answers: ["Rocket", "Star-Lord", "Drax"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce culoare are sabia laser a lui Mace Windu in 'Star Wars'?",
  correct_answer: "Mov",
  incorrect_answers: ["Verde", "Albastru", "Rosu"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "In ce film apare melodia 'My Heart Will Go On'?",
  correct_answer: "Titanic",
  incorrect_answers: ["The Bodyguard", "Ghost", "Pretty Woman"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste majordomul loial al lui Batman?",
  correct_answer: "Alfred",
  incorrect_answers: ["Robin", "Gordon", "Lucius"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce film spune povestea lui Mozart?",
  correct_answer: "Amadeus",
  incorrect_answers: ["Immortal Beloved", "Shine", "The Pianist"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Care este filmul cu cele mai mari incasari din toate timpurile (pana in 2023)?",
  correct_answer: "Avatar",
  incorrect_answers: ["Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce printesa Disney are un pantof de sticla?",
  correct_answer: "Cenusareasa",
  incorrect_answers: ["Snow White", "Belle", "Aurora"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cine a jucat rolul lui Forrest Gump?",
  correct_answer: "Tom Hanks",
  incorrect_answers: ["Harrison Ford", "Bill Murray", "Kevin Costner"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "In 'The Silence of the Lambs', cum se numeste criminalul in serie?",
  correct_answer: "Hannibal Lecter",
  incorrect_answers: ["Norman Bates", "Jack Torrance", "Patrick Bateman"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce oras fictiv este casa lui Superman?",
  correct_answer: "Metropolis",
  incorrect_answers: ["Gotham", "Star City", "Smallville"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce film are o masina DeLorean care calatoreste in timp?",
  correct_answer: "Back to the Future",
  incorrect_answers: ["Blade Runner", "Total Recall", "The Terminator"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'The Godfather'?",
  correct_answer: "Francis Ford Coppola",
  incorrect_answers: ["Martin Scorsese", "Sergio Leone", "Brian De Palma"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce animal este Simba in 'The Lion King'?",
  correct_answer: "Leu",
  incorrect_answers: ["Tigru", "Ghepard", "Leopard"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In ce film apare o minge de volei numita Wilson?",
  correct_answer: "Cast Away",
  incorrect_answers: ["The Terminal", "Apollo 13", "Saving Private Ryan"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cum se numeste hotelul din 'The Shining'?",
  correct_answer: "Overlook Hotel",
  incorrect_answers: ["Bates Motel", "Grand Budapest Hotel", "Hotel California"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cine este personajul negativ din '101 Dalmatians'?",
  correct_answer: "Cruella de Vil",
  incorrect_answers: ["Ursula", "Maleficent", "Evil Queen"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce actrita a jucat-o pe Katniss Everdeen in 'The Hunger Games'?",
  correct_answer: "Jennifer Lawrence",
  incorrect_answers: ["Emma Watson", "Shailene Woodley", "Kristen Stewart"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Ce film a castigat primul Oscar din istorie pentru Cel mai bun film?",
  correct_answer: "Wings",
  incorrect_answers: ["Sunrise", "Metropolis", "The Jazz Singer"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce jucarii prind viata in 'Toy Story'?",
  correct_answer: "Toate",
  incorrect_answers: ["Doar Woody", "Doar Buzz", "Niciuna"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Din ce film este replica 'You can't handle the truth!'?",
  correct_answer: "A Few Good Men",
  incorrect_answers: ["Top Gun", "Jerry Maguire", "Rain Man"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Care este numele real al lui The Rock?",
  correct_answer: "Dwayne Johnson",
  incorrect_answers: ["Steve Austin", "John Cena", "Dave Bautista"],
},
// --- FILME (BATCH 2 - EXTINS) ---
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste cainele din 'The Wizard of Oz'?",
  correct_answer: "Toto",
  incorrect_answers: ["Lassie", "Buddy", "Rex"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In 'Fight Club', care este prima regula a Fight Club?",
  correct_answer: "Nu vorbesti despre Fight Club",
  incorrect_answers: ["Nu te bati fara tricou", "Doi baieti la o lupta", "Luptele continua cat este nevoie"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Ce film a castigat Oscarul pentru Cel mai bun film in 2020 (primul film intr-o limba non-engleza care a castigat)?",
  correct_answer: "Parasite",
  incorrect_answers: ["Roma", "1917", "Jojo Rabbit"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce actor il joaca pe Wolverine in filmele X-Men?",
  correct_answer: "Hugh Jackman",
  incorrect_answers: ["Christian Bale", "Tom Hardy", "Ben Affleck"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste insula din 'Jurassic Park'?",
  correct_answer: "Isla Nublar",
  incorrect_answers: ["Isla Sorna", "Isla Mujeres", "Isla Grande"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'E.T. the Extra-Terrestrial'?",
  correct_answer: "Steven Spielberg",
  incorrect_answers: ["George Lucas", "James Cameron", "Tim Burton"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste omul de zapada din 'Frozen'?",
  correct_answer: "Olaf",
  incorrect_answers: ["Sven", "Kristoff", "Hans"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce film il are ca personaj pe 'Donnie Darko'?",
  correct_answer: "Donnie Darko",
  incorrect_answers: ["Nightcrawler", "Prisoners", "Zodiac"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "In 'The Matrix', cum se numeste nava condusa de Morpheus?",
  correct_answer: "Nebuchadnezzar",
  incorrect_answers: ["Icarus", "Prometheus", "Nostromo"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cine este principalul antagonist in 'Star Wars: A New Hope'?",
  correct_answer: "Darth Vader",
  incorrect_answers: ["Emperor Palpatine", "Kylo Ren", "Darth Maul"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Din ce film este replica 'I see dead people'?",
  correct_answer: "The Sixth Sense",
  incorrect_answers: ["The Others", "Poltergeist", "Ghostbusters"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cum se numeste demonul din 'The Exorcist'?",
  correct_answer: "Pazuzu",
  incorrect_answers: ["Beelzebub", "Azazel", "Lucifer"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce supererou este Peter Parker?",
  correct_answer: "Spider-Man",
  incorrect_answers: ["Superman", "Batman", "Flash"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cine l-a jucat pe Neo in 'The Matrix'?",
  correct_answer: "Keanu Reeves",
  incorrect_answers: ["Will Smith", "Brad Pitt", "Tom Cruise"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Ce film este bazat pe un roman de Stephen King despre un clovn?",
  correct_answer: "It",
  incorrect_answers: ["The Shining", "Carrie", "Misery"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste leul din 'The Chronicles of Narnia'?",
  correct_answer: "Aslan",
  incorrect_answers: ["Simba", "Mufasa", "Scar"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In ce film apare un personaj numit 'The Dude'?",
  correct_answer: "The Big Lebowski",
  incorrect_answers: ["Fargo", "No Country for Old Men", "Burn After Reading"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'Blade Runner' (1982)?",
  correct_answer: "Ridley Scott",
  incorrect_answers: ["Denis Villeneuve", "James Cameron", "George Miller"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce film este despre un parc tematic cu dinozauri?",
  correct_answer: "Jurassic Park",
  incorrect_answers: ["King Kong", "Godzilla", "The Land Before Time"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste inelul din 'The Lord of the Rings'?",
  correct_answer: "The One Ring",
  incorrect_answers: ["The Ring of Power", "The Precious Ring", "The Golden Ring"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "In 'Goodfellas', cum se numeste personajul jucat de Ray Liotta?",
  correct_answer: "Henry Hill",
  incorrect_answers: ["Tommy DeVito", "Jimmy Conway", "Paul Cicero"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In ce film apare un personaj numit 'Buzz Lightyear'?",
  correct_answer: "Toy Story",
  incorrect_answers: ["Cars", "Monsters, Inc.", "The Incredibles"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cine a jucat Joker-ul in filmul 'Batman' din 1989?",
  correct_answer: "Jack Nicholson",
  incorrect_answers: ["Heath Ledger", "Jared Leto", "Cesar Romero"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Din ce film este replica 'You talking to me?'?",
  correct_answer: "Taxi Driver",
  incorrect_answers: ["Raging Bull", "Goodfellas", "Mean Streets"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste zana din 'Peter Pan'?",
  correct_answer: "Tinker Bell",
  incorrect_answers: ["Silvermist", "Fawn", "Iridessa"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce film este plasat pe planeta Pandora?",
  correct_answer: "Avatar",
  incorrect_answers: ["Star Trek", "Guardians of the Galaxy", "Alien"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'Inception'?",
  correct_answer: "Christopher Nolan",
  incorrect_answers: ["Quentin Tarantino", "David Fincher", "Wes Anderson"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce film are un personaj numit 'Shrek'?",
  correct_answer: "Shrek",
  incorrect_answers: ["Ice Age", "Madagascar", "Kung Fu Panda"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste hotelul din 'Pretty Woman'?",
  correct_answer: "Regent Beverly Wilshire",
  incorrect_answers: ["The Plaza", "The Ritz", "The Waldorf Astoria"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Ce film a castigat Oscarul pentru Cel mai bun film in 2017 (dupa o incurcatura)?",
  correct_answer: "Moonlight",
  incorrect_answers: ["La La Land", "Arrival", "Manchester by the Sea"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cine este personajul principal din 'The Lion King'?",
  correct_answer: "Simba",
  incorrect_answers: ["Mufasa", "Nala", "Scar"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In ce film apare melodia 'Eye of the Tiger'?",
  correct_answer: "Rocky III",
  incorrect_answers: ["The Karate Kid", "Top Gun", "Flashdance"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine l-a jucat pe Hannibal Lecter in 'The Silence of the Lambs'?",
  correct_answer: "Anthony Hopkins",
  incorrect_answers: ["Brian Cox", "Mads Mikkelsen", "Jeremy Irons"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In ce film apare un personaj numit 'Dory'?",
  correct_answer: "Finding Nemo",
  incorrect_answers: ["The Little Mermaid", "Shark Tale", "Moana"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste nava spatiala din 'Alien'?",
  correct_answer: "Nostromo",
  incorrect_answers: ["Sulaco", "Prometheus", "Covenant"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'The Grand Budapest Hotel'?",
  correct_answer: "Wes Anderson",
  incorrect_answers: ["Paul Thomas Anderson", "Coen Brothers", "Spike Jonze"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In ce film apare un personaj numit 'Elsa'?",
  correct_answer: "Frozen",
  incorrect_answers: ["Tangled", "Brave", "Moana"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Din ce film este citatul 'Frankly, my dear, I don't give a damn'?",
  correct_answer: "Gone with the Wind",
  incorrect_answers: ["Casablanca", "Citizen Kane", "The Wizard of Oz"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine l-a jucat pe Tyler Durden in 'Fight Club'?",
  correct_answer: "Brad Pitt",
  incorrect_answers: ["Edward Norton", "Jared Leto", "Matt Damon"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In ce film apare un personaj numit 'Lightning McQueen'?",
  correct_answer: "Cars",
  incorrect_answers: ["Planes", "Turbo", "Herbie"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In ce film apare melodia 'Unchained Melody'?",
  correct_answer: "Ghost",
  incorrect_answers: ["Dirty Dancing", "Pretty Woman", "Top Gun"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'Schindler's List'?",
  correct_answer: "Steven Spielberg",
  incorrect_answers: ["Roman Polanski", "Martin Scorsese", "Francis Ford Coppola"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce film are un personaj numit 'Gru'?",
  correct_answer: "Despicable Me",
  incorrect_answers: ["Megamind", "The Incredibles", "Minions"],
},
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "In ce film apare replica 'Hasta la vista, baby'?",
    correct_answer: "Terminator 2: Judgment Day",
    incorrect_answers: ["Total Recall", "Predator", "Commando"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a jucat rolul personajului Jack Torrance in 'The Shining'?",
    correct_answer: "Jack Nicholson",
    incorrect_answers: ["Robert De Niro", "Al Pacino", "Dustin Hoffman"],
  },

  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "In ce film apare un personaj numit 'Po'?",
    correct_answer: "Kung Fu Panda",
    incorrect_answers: ["Mulan", "Raya and the Last Dragon", "Turning Red"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "In ce film apare melodia 'Stayin' Alive'?",
    correct_answer: "Saturday Night Fever",
    incorrect_answers: ["Grease", "Footloose", "Flashdance"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a regizat 'Pulp Fiction'?",
    correct_answer: "Quentin Tarantino",
    incorrect_answers: ["Guy Ritchie", "Robert Rodriguez", "Coen Brothers"],
  },
  // --- MUZICA (LOT 1 - MIXT) ---
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Care cantareata este cunoscuta drept 'Regina Pop-ului'?",
    correct_answer: "Madonna",
    incorrect_answers: ["Lady Gaga", "Beyoncé", "Britney Spears"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cine a scris piesa 'Bohemian Rhapsody'?",
    correct_answer: "Freddie Mercury",
    incorrect_answers: ["Elton John", "David Bowie", "Paul McCartney"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce trupa a interpretat 'Dancing Queen'?",
    correct_answer: "ABBA",
    incorrect_answers: ["The Beatles", "Bee Gees", "Fleetwood Mac"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Care este numele real al lui Lady Gaga?",
    correct_answer: "Stefani Germanotta",
    incorrect_answers: ["Robyn Fenty", "Katheryn Hudson", "Alecia Moore"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cate corzi are o chitara standard?",
    correct_answer: "6",
    incorrect_answers: ["4", "5", "7"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce artist canadian a cantat piesa 'Baby'?",
    correct_answer: "Justin Bieber",
    incorrect_answers: ["Drake", "The Weeknd", "Shawn Mendes"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cine este solistul trupei Coldplay?",
    correct_answer: "Chris Martin",
    incorrect_answers: ["Thom Yorke", "Bono", "Adam Levine"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "In ce an a murit Elvis Presley?",
    correct_answer: "1977",
    incorrect_answers: ["1975", "1980", "1969"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Fanii carei vedete pop se numesc 'Swifties'?",
    correct_answer: "Taylor Swift",
    incorrect_answers: ["Ariana Grande", "Katy Perry", "Selena Gomez"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Ce rapper a lansat albumul 'The Marshall Mathers LP'?",
    correct_answer: "Eminem",
    incorrect_answers: ["50 Cent", "Jay-Z", "Dr. Dre"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Ce compozitor clasic a surzit in ultimii ani de viata?",
    correct_answer: "Ludwig van Beethoven",
    incorrect_answers: ["Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Frederic Chopin"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine a cantat 'I Will Always Love You' in filmul 'The Bodyguard'?",
    correct_answer: "Whitney Houston",
    incorrect_answers: ["Mariah Carey", "Celine Dion", "Aretha Franklin"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Al carei trupe grunge a fost solist Kurt Cobain?",
    correct_answer: "Nirvana",
    incorrect_answers: ["Pearl Jam", "Soundgarden", "Alice in Chains"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "La ce instrument canta Lizzo?",
    correct_answer: "Flaut",
    incorrect_answers: ["Vioara", "Pian", "Saxofon"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Care este cel mai vandut album din toate timpurile?",
    correct_answer: "Thriller (Michael Jackson)",
    incorrect_answers: ["Back in Black (AC/DC)", "The Dark Side of the Moon (Pink Floyd)", "Rumours (Fleetwood Mac)"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cine este cunoscut drept 'Nasul muzicii Soul' (Godfather of Soul)?",
    correct_answer: "James Brown",
    incorrect_answers: ["Ray Charles", "Otis Redding", "Marvin Gaye"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce trupa de fete britanica a avut un hit cu piesa 'Wannabe'?",
    correct_answer: "Spice Girls",
    incorrect_answers: ["Little Mix", "Destiny's Child", "The Pussycat Dolls"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Din ce tara provine trupa U2?",
    correct_answer: "Irlanda",
    incorrect_answers: ["Marea Britanie", "SUA", "Australia"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a fost primul baterist al trupei The Beatles?",
    correct_answer: "Pete Best",
    incorrect_answers: ["Ringo Starr", "Keith Moon", "John Bonham"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine canta hitul 'Hello'?",
    correct_answer: "Adele",
    incorrect_answers: ["Sia", "Rihanna", "Amy Winehouse"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Ce artist este cunoscut sub numele de 'Prince'?",
    correct_answer: "Prince Rogers Nelson",
    incorrect_answers: ["Michael Jackson", "David Bowie", "Elton John"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Cate clape are un pian standard?",
    correct_answer: "88",
    incorrect_answers: ["64", "76", "100"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce melodie incepe cu versurile 'Is this the real life? Is this just fantasy?'?",
    correct_answer: "Bohemian Rhapsody",
    incorrect_answers: ["Stairway to Heaven", "Imagine", "Hotel California"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cine este solistul trupei The Rolling Stones?",
    correct_answer: "Mick Jagger",
    incorrect_answers: ["Keith Richards", "Robert Plant", "Steven Tyler"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Care a fost primul videoclip muzical difuzat la MTV?",
    correct_answer: "Video Killed the Radio Star",
    incorrect_answers: ["Thriller", "Take on Me", "Billie Jean"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce cantaret este faimos pentru pasul de dans 'Moonwalk'?",
    correct_answer: "Michael Jackson",
    incorrect_answers: ["Usher", "Justin Timberlake", "Bruno Mars"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Ce festival faimos a avut loc in 1969?",
    correct_answer: "Woodstock",
    incorrect_answers: ["Glastonbury", "Coachella", "Lollapalooza"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a compus 'Anotimpurile' (The Four Seasons)?",
    correct_answer: "Antonio Vivaldi",
    incorrect_answers: ["Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cu cine este casatorita Beyonce?",
    correct_answer: "Jay-Z",
    incorrect_answers: ["Kanye West", "Drake", "P. Diddy"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Pentru ce gen muzical este faimos Bob Marley?",
    correct_answer: "Reggae",
    incorrect_answers: ["Jazz", "Blues", "Rap"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Ce album Pink Floyd are o prisma pe coperta?",
    correct_answer: "The Dark Side of the Moon",
    incorrect_answers: ["The Wall", "Wish You Were Here", "Animals"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine a inregistrat hitul 'Shape of You'?",
    correct_answer: "Ed Sheeran",
    incorrect_answers: ["Sam Smith", "Harry Styles", "Lewis Capaldi"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Ce trupa are ca logo o gura cu limba scoasa?",
    correct_answer: "The Rolling Stones",
    incorrect_answers: ["KISS", "The Beatles", "Led Zeppelin"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Cum se numeste gama cu cinci note pe octava?",
    correct_answer: "Gama pentatonica",
    incorrect_answers: ["Gama cromatica", "Gama diatonica", "Gama minora"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce legenda a muzicii country a cantat 'Jolene'?",
    correct_answer: "Dolly Parton",
    incorrect_answers: ["Reba McEntire", "Shania Twain", "Carrie Underwood"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cine este poreclit 'Rocket Man'?",
    correct_answer: "Elton John",
    incorrect_answers: ["David Bowie", "Freddie Mercury", "Billy Joel"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Ce rapper a fost impuscat mortal in Las Vegas in 1996?",
    correct_answer: "Tupac Shakur",
    incorrect_answers: ["Notorious B.I.G.", "Eazy-E", "XXXtentacion"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce instrument muzical are clape albe si negre?",
    correct_answer: "Pian",
    incorrect_answers: ["Chitara", "Vioara", "Trompeta"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cum se numea trupa din care facea parte Beyonce inainte de cariera solo?",
    correct_answer: "Destiny's Child",
    incorrect_answers: ["TLC", "En Vogue", "The Supremes"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a scris versurile pentru musicalul 'Hamilton'?",
    correct_answer: "Lin-Manuel Miranda",
    incorrect_answers: ["Andrew Lloyd Webber", "Stephen Sondheim", "Tim Rice"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine a cantat 'Single Ladies (Put a Ring on It)'?",
    correct_answer: "Beyoncé",
    incorrect_answers: ["Rihanna", "Alicia Keys", "Jennifer Lopez"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Ce trupa a lansat 'Smells Like Teen Spirit'?",
    correct_answer: "Nirvana",
    incorrect_answers: ["Pearl Jam", "Foo Fighters", "Green Day"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Care este cea mai grava voce barbateasca?",
    correct_answer: "Bas",
    incorrect_answers: ["Tenor", "Bariton", "Alto"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine a lansat hitul 'Blinding Lights'?",
    correct_answer: "The Weeknd",
    incorrect_answers: ["Drake", "Post Malone", "Travis Scott"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cu ce instrument este asociat Louis Armstrong?",
    correct_answer: "Trompeta",
    incorrect_answers: ["Saxofon", "Pian", "Tobe"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "In ce an s-a destramat trupa The Beatles?",
    correct_answer: "1970",
    incorrect_answers: ["1969", "1971", "1968"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce nationalitate are Justin Bieber?",
    correct_answer: "Canadiana",
    incorrect_answers: ["Americana", "Britanica", "Australiana"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cine canta 'Rolling in the Deep'?",
    correct_answer: "Adele",
    incorrect_answers: ["Katy Perry", "Taylor Swift", "Lady Gaga"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Cine este cunoscuta drept 'Imparateasa Blues-ului'?",
    correct_answer: "Bessie Smith",
    incorrect_answers: ["Billie Holiday", "Ella Fitzgerald", "Aretha Franklin"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce trupa canta 'Yellow Submarine'?",
    correct_answer: "The Beatles",
    incorrect_answers: ["The Rolling Stones", "The Who", "The Kinks"],
  },
  // --- MUZICA (LOT 2 - EXTINS) ---
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Care cantareata este cunoscuta drept 'Material Girl'?",
    correct_answer: "Madonna",
    incorrect_answers: ["Cyndi Lauper", "Cher", "Kylie Minogue"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cine este solistul trupei Guns N' Roses?",
    correct_answer: "Axl Rose",
    incorrect_answers: ["Slash", "Steven Tyler", "Jon Bon Jovi"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Ce compozitor clasic a scris 'Flautul Fermecat'?",
    correct_answer: "Wolfgang Amadeus Mozart",
    incorrect_answers: ["Beethoven", "Bach", "Haydn"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce melodie contine miscarea de dans 'Gangnam Style'?",
    correct_answer: "Gangnam Style",
    incorrect_answers: ["Gentleman", "Despacito", "Macarena"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Ce trupa a cantat 'Hotel California'?",
    correct_answer: "Eagles",
    incorrect_answers: ["Lynyrd Skynyrd", "Fleetwood Mac", "The Doors"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Care este numele real al DJ-ului Avicii?",
    correct_answer: "Tim Bergling",
    incorrect_answers: ["Calvin Harris", "David Guetta", "Martin Garrix"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine canta 'Bad Guy'?",
    correct_answer: "Billie Eilish",
    incorrect_answers: ["Lorde", "Dua Lipa", "Halsey"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Ce artist a lansat albumul 'Purple Rain'?",
    correct_answer: "Prince",
    incorrect_answers: ["Michael Jackson", "Stevie Wonder", "Lionel Richie"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Ce trupa heavy metal a lansat 'Black Album'?",
    correct_answer: "Metallica",
    incorrect_answers: ["Iron Maiden", "Megadeth", "Slayer"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Care membra Spice Girls era cunoscuta ca 'Posh Spice'?",
    correct_answer: "Victoria Beckham",
    incorrect_answers: ["Mel B", "Geri Halliwell", "Emma Bunton"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cine a cantat 'Respect'?",
    correct_answer: "Aretha Franklin",
    incorrect_answers: ["Diana Ross", "Tina Turner", "Etta James"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Ce trupa se numea initial 'Kara's Flowers'?",
    correct_answer: "Maroon 5",
    incorrect_answers: ["Coldplay", "Imagine Dragons", "OneRepublic"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine este tatal lui Miley Cyrus?",
    correct_answer: "Billy Ray Cyrus",
    incorrect_answers: ["Johnny Cash", "Willie Nelson", "Garth Brooks"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Ce melodie incepe cu versurile 'Is this the real life?'",
    correct_answer: "Bohemian Rhapsody",
    incorrect_answers: ["Somebody to Love", "We Are the Champions", "Don't Stop Me Now"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Cine este bateristul trupei Blink-182?",
    correct_answer: "Travis Barker",
    incorrect_answers: ["Dave Grohl", "Tre Cool", "Taylor Hawkins"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine a cantat 'Umbrella'?",
    correct_answer: "Rihanna",
    incorrect_answers: ["Beyoncé", "Ciara", "Katy Perry"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "La ce instrument a cantat Jimi Hendrix?",
    correct_answer: "Chitara",
    incorrect_answers: ["Tobe", "Bas", "Pian"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Ce rapper a fondat casa de discuri 'OVO Sound'?",
    correct_answer: "Drake",
    incorrect_answers: ["Kanye West", "Jay-Z", "Lil Wayne"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine este cunoscut drept 'Piano Man'?",
    correct_answer: "Billy Joel",
    incorrect_answers: ["Elton John", "Stevie Wonder", "Ray Charles"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Ce cantareata britanica a murit la varsta de 27 de ani in 2011?",
    correct_answer: "Amy Winehouse",
    incorrect_answers: ["Janis Joplin", "Whitney Houston", "Aaliyah"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Care simfonie este cunoscuta drept simfonia 'Corala'?",
    correct_answer: "Simfonia a 9-a a lui Beethoven",
    incorrect_answers: ["Simfonia a 40-a a lui Mozart", "Simfonia a 5-a a lui Mahler", "Simfonia a 8-a a lui Schubert"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce trupa canta 'We Will Rock You'?",
    correct_answer: "Queen",
    incorrect_answers: ["AC/DC", "KISS", "Bon Jovi"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Care a fost prenumele compozitorului Bach?",
    correct_answer: "Johann",
    incorrect_answers: ["Ludwig", "Wolfgang", "Franz"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Ce artist are o baza de fani numita 'Little Monsters'?",
    correct_answer: "Lady Gaga",
    incorrect_answers: ["Katy Perry", "Nicki Minaj", "Miley Cyrus"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine a cantat 'Thriller'?",
    correct_answer: "Michael Jackson",
    incorrect_answers: ["Prince", "Stevie Wonder", "Lionel Richie"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Ce trupa este faimoasa pentru melodia 'Sweet Child O' Mine'?",
    correct_answer: "Guns N' Roses",
    incorrect_answers: ["Aerosmith", "Def Leppard", "Motley Crue"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Ce rapper este cunoscut sub numele de 'Slim Shady'?",
    correct_answer: "Eminem",
    incorrect_answers: ["Dr. Dre", "Snoop Dogg", "Ice Cube"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine canta 'Shake It Off'?",
    correct_answer: "Taylor Swift",
    incorrect_answers: ["Selena Gomez", "Demi Lovato", "Ariana Grande"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cine a fost solistul trupei The Police?",
    correct_answer: "Sting",
    incorrect_answers: ["Bono", "Phil Collins", "Rod Stewart"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Ce tara a castigat Eurovisionul in 1974 cu trupa ABBA?",
    correct_answer: "Suedia",
    incorrect_answers: ["Norvegia", "Danemarca", "Finlanda"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce instrument are 4 corzi si este des folosit in Hawaii?",
    correct_answer: "Ukulele",
    incorrect_answers: ["Banjo", "Chitara", "Vioara"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Ce melodie a fost un hit pentru Britney Spears in 1998?",
    correct_answer: "Baby One More Time",
    incorrect_answers: ["Toxic", "Oops!... I Did It Again", "Crazy"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Ce trupa a lansat albumul 'The Joshua Tree'?",
    correct_answer: "U2",
    incorrect_answers: ["R.E.M.", "Radiohead", "The Cure"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine canta 'Firework'?",
    correct_answer: "Katy Perry",
    incorrect_answers: ["Rihanna", "Lady Gaga", "Sia"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Cine este solistul trupei Aerosmith?",
    correct_answer: "Steven Tyler",
    incorrect_answers: ["Mick Jagger", "Robert Plant", "Ozzy Osbourne"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Cum se numeste solistul trupei System of a Down?",
    correct_answer: "Serj Tankian",
    incorrect_answers: ["Daron Malakian", "Chester Bennington", "Jonathan Davis"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Ce cantaret este cunoscut drept 'Regele Rock and Roll-ului'?",
    correct_answer: "Elvis Presley",
    incorrect_answers: ["Chuck Berry", "Little Richard", "Buddy Holly"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Ce trupa a cantat 'Wonderwall'?",
    correct_answer: "Oasis",
    incorrect_answers: ["Blur", "The Verve", "Radiohead"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a scris melodia 'Hallelujah'?",
    correct_answer: "Leonard Cohen",
    incorrect_answers: ["Bob Dylan", "Paul Simon", "Jeff Buckley"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Cine canta 'Thinking Out Loud'?",
    correct_answer: "Ed Sheeran",
    incorrect_answers: ["Sam Smith", "John Legend", "Bruno Mars"],
  },
  // --- SPORT (LOT 1 - MIXT) ---
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce sport se joaca la Wimbledon?",
    correct_answer: "Tenis",
    incorrect_answers: ["Golf", "Cricket", "Fotbal"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Cat de lung este un maraton?",
    correct_answer: "42.195 km",
    incorrect_answers: ["40 km", "50 km", "21 km"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "In ce sport ai executa un slam dunk?",
    correct_answer: "Baschet",
    incorrect_answers: ["Volei", "Tenis", "Baseball"],
  },
  // --- SPORT (LOT 1 - MIXT) ---
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Ce tara a castigat prima Cupa Mondiala FIFA in 1930?",
    correct_answer: "Uruguay",
    incorrect_answers: ["Brazilia", "Argentina", "Italia"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Cine detine recordul pentru cele mai multe medalii de aur olimpice?",
    correct_answer: "Michael Phelps",
    incorrect_answers: ["Usain Bolt", "Carl Lewis", "Mark Spitz"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Care este sportul national al Japoniei?",
    correct_answer: "Luptele Sumo",
    incorrect_answers: ["Karate", "Judo", "Baseball"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce echipa din NBA este cunoscuta sub numele de 'Lakers'?",
    correct_answer: "Los Angeles",
    incorrect_answers: ["Chicago", "New York", "Boston"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a castigat Campionatul Mondial de Formula 1 in 2021?",
    correct_answer: "Max Verstappen",
    incorrect_answers: ["Lewis Hamilton", "Sebastian Vettel", "Valtteri Bottas"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Cati jucatori are o echipa de baseball pe teren?",
    correct_answer: "9",
    incorrect_answers: ["11", "7", "10"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce boxer a fost cunoscut drept 'The Greatest'?",
    correct_answer: "Muhammad Ali",
    incorrect_answers: ["Mike Tyson", "Floyd Mayweather", "George Foreman"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce obiect este lovit in Badminton?",
    correct_answer: "Fluturasul (Shuttlecock)",
    incorrect_answers: ["Mingea", "Pucul", "Bila"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "La golf, cum se numeste un scor cu o lovitura sub par?",
    correct_answer: "Birdie",
    incorrect_answers: ["Eagle", "Bogey", "Albatross"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce tara a castigat cele mai multe Cupe Mondiale la fotbal?",
    correct_answer: "Brazilia",
    incorrect_answers: ["Germania", "Italia", "Argentina"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce sport se desfasoara intr-un ring?",
    correct_answer: "Box",
    incorrect_answers: ["Tenis", "Inot", "Golf"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Care este break-ul maxim in Snooker?",
    correct_answer: "147",
    incorrect_answers: ["155", "100", "180"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Cine este cunoscut sub numele de 'CR7'?",
    correct_answer: "Cristiano Ronaldo",
    incorrect_answers: ["Lionel Messi", "Ronaldinho", "Neymar"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "In ce sport se foloseste un tac?",
    correct_answer: "Biliard/Pool",
    incorrect_answers: ["Golf", "Hochei", "Cricket"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Cate minute dureaza un meci de rugby?",
    correct_answer: "80",
    incorrect_answers: ["90", "60", "70"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "In ce an au avut loc primele Jocuri Olimpice moderne?",
    correct_answer: "1896",
    incorrect_answers: ["1900", "1924", "1888"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce forma are o minge de rugby?",
    correct_answer: "Ovala",
    incorrect_answers: ["Rotunda", "Patrata", "Triunghiulara"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce echipa a castigat Super Bowl in 2020?",
    correct_answer: "Kansas City Chiefs",
    incorrect_answers: ["San Francisco 49ers", "New England Patriots", "Tampa Bay Buccaneers"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Cine este cel mai bun marcator din istoria NBA (valabil in 2023)?",
    correct_answer: "LeBron James",
    incorrect_answers: ["Kareem Abdul-Jabbar", "Karl Malone", "Kobe Bryant"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "In ce sport se foloseste un puc?",
    correct_answer: "Hochei pe gheata",
    incorrect_answers: ["Hochei pe iarba", "Fotbal", "Lacrosse"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce jucator de tenis a castigat cele mai multe titluri de Grand Slam (Masculin)?",
    correct_answer: "Novak Djokovic",
    incorrect_answers: ["Roger Federer", "Rafael Nadal", "Pete Sampras"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Ce oras a gazduit Jocurile Olimpice de vara din 2008?",
    correct_answer: "Beijing",
    incorrect_answers: ["Londra", "Atena", "Sydney"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Cate gauri sunt intr-o runda standard de golf?",
    correct_answer: "18",
    incorrect_answers: ["9", "12", "20"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Care este porecla echipei de rugby a Noii Zeelande?",
    correct_answer: "All Blacks",
    incorrect_answers: ["Springboks", "Wallabies", "Pumas"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a castigat Balonul de Aur in 2023?",
    correct_answer: "Lionel Messi",
    incorrect_answers: ["Erling Haaland", "Kylian Mbappé", "Kevin De Bruyne"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "In ce tara se afla FC Barcelona?",
    correct_answer: "Spania",
    incorrect_answers: ["Italia", "Franta", "Portugalia"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "La bowling, cum se numeste cand dobori toate popicele dintr-o singura lovitura?",
    correct_answer: "Strike",
    incorrect_answers: ["Spare", "Turkey", "Split"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Ce cal a castigat Tripla Coroana in 1973?",
    correct_answer: "Secretariat",
    incorrect_answers: ["Seabiscuit", "American Pharoah", "Man o' War"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce culoare are cartonasul care indica eliminarea la fotbal?",
    correct_answer: "Rosu",
    incorrect_answers: ["Galben", "Albastru", "Negru"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Cati jucatori sunt intr-o echipa de volei (pe teren)?",
    correct_answer: "6",
    incorrect_answers: ["5", "7", "4"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a fost prima persoana care a alergat o mila in mai putin de 4 minute?",
    correct_answer: "Roger Bannister",
    incorrect_answers: ["Usain Bolt", "Jesse Owens", "Carl Lewis"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce sport implica deplasarea pe valuri folosind o placa?",
    correct_answer: "Surfing",
    incorrect_answers: ["Skateboarding", "Snowboarding", "Wakeboarding"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Care este diametrul unui inel de baschet?",
    correct_answer: "18 inci (45 cm)",
    incorrect_answers: ["16 inci", "20 inci", "15 inci"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Ce tara a castigat Cupa Mondiala de Rugby in 2019?",
    correct_answer: "Africa de Sud",
    incorrect_answers: ["Anglia", "Noua Zeelanda", "Australia"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce lovesti in baseball?",
    correct_answer: "Mingea",
    incorrect_answers: ["Pucul", "Fluturasul", "Birdie-ul"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Cine este cel mai rapid om din istorie?",
    correct_answer: "Usain Bolt",
    incorrect_answers: ["Tyson Gay", "Yohan Blake", "Justin Gatlin"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Ce echipa din NFL are cele mai multe victorii la Super Bowl (la egalitate)?",
    correct_answer: "New England Patriots & Pittsburgh Steelers",
    incorrect_answers: ["Dallas Cowboys & SF 49ers", "Green Bay Packers & NY Giants", "Denver Broncos & Raiders"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Pentru ce sport este faimos Tiger Woods?",
    correct_answer: "Golf",
    incorrect_answers: ["Tenis", "Baschet", "Baseball"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce jucatoare de tenis are cele mai multe titluri de Grand Slam (Era Open)?",
    correct_answer: "Serena Williams",
    incorrect_answers: ["Steffi Graf", "Martina Navratilova", "Venus Williams"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Unde au avut loc Jocurile Olimpice de vara din 2016?",
    correct_answer: "Rio de Janeiro",
    incorrect_answers: ["Londra", "Tokyo", "Paris"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "In ce sport are loc Turul Frantei?",
    correct_answer: "Ciclism",
    incorrect_answers: ["Alergare", "Inot", "Curse auto"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Cate puncte valoreaza un touchdown in fotbalul american?",
    correct_answer: "6",
    incorrect_answers: ["7", "3", "2"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Cine este singurul fotbalist care a castigat 3 Cupe Mondiale?",
    correct_answer: "Pelé",
    incorrect_answers: ["Maradona", "Zidane", "Ronaldo"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce sport se joaca pe gheata cu maturi si o piatra?",
    correct_answer: "Curling",
    incorrect_answers: ["Hochei", "Patinaj", "Bobsleigh"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce tara a gazduit Cupa Mondiala FIFA 2014?",
    correct_answer: "Brazilia",
    incorrect_answers: ["Rusia", "Africa de Sud", "Germania"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Care este scorul maxim posibil intr-un joc de bowling cu 10 popice?",
    correct_answer: "300",
    incorrect_answers: ["200", "250", "400"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce piesa de sah se misca in forma de L?",
    correct_answer: "Calul",
    incorrect_answers: ["Nebunul", "Tura", "Regele"],
  },
  // --- SPORT (LOT 2 - EXTINS) ---
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Care este numele trofeului acordat campioanei NHL?",
    correct_answer: "Cupa Stanley",
    incorrect_answers: ["Trofeul Vince Lombardi", "Trofeul Larry O'Brien", "Trofeul Commissioner"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce tara a castigat Cupa Mondiala FIFA 2022?",
    correct_answer: "Argentina",
    incorrect_answers: ["Franta", "Brazilia", "Croatia"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "La ce inaltime fata de sol se afla un inel de baschet regulamentar?",
    correct_answer: "10 picioare (3.05 metri)",
    incorrect_answers: ["9 picioare", "11 picioare", "12 picioare"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Pentru ce sport este faimos Michael Jordan?",
    correct_answer: "Baschet",
    incorrect_answers: ["Baseball", "Golf", "Fotbal american"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Care este suprafata de joc la Roland Garros (French Open)?",
    correct_answer: "Zgura",
    incorrect_answers: ["Iarba", "Hard", "Covor sintetic"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Cine este singurul boxer care s-a retras neinvins ca si campion la categoria grea?",
    correct_answer: "Rocky Marciano",
    incorrect_answers: ["Muhammad Ali", "Mike Tyson", "Floyd Mayweather"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce culoare are masina Ferrari de Formula 1?",
    correct_answer: "Rosu",
    incorrect_answers: ["Argintiu", "Albastru", "Galben"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Cate reprize sunt intr-un meci de hochei pe gheata?",
    correct_answer: "3",
    incorrect_answers: ["2", "4", "5"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Ce tara a castigat cele mai multe medalii de aur in istoria Jocurilor Olimpice de vara?",
    correct_answer: "SUA",
    incorrect_answers: ["China", "Rusia", "Germania"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce sport implica un 'sah mat'?",
    correct_answer: "Sah",
    incorrect_answers: ["Dame", "Table", "Go"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Care este porecla echipei nationale de rugby a Australiei?",
    correct_answer: "Wallabies",
    incorrect_answers: ["All Blacks", "Springboks", "Kangaroos"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "In ce an au incheiat Chicago Cubs seceta de 108 ani la World Series?",
    correct_answer: "2016",
    incorrect_answers: ["2015", "2017", "2004"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Cate inele sunt in logo-ul olimpic?",
    correct_answer: "5",
    incorrect_answers: ["4", "6", "7"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Carui jucator de golf i se spune 'Lefty'?",
    correct_answer: "Phil Mickelson",
    incorrect_answers: ["Tiger Woods", "Bubba Watson", "Rory McIlroy"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Cine detine recordul pentru cel mai rapid knockout din istoria UFC (5 secunde)?",
    correct_answer: "Jorge Masvidal",
    incorrect_answers: ["Conor McGregor", "Ronda Rousey", "Francis Ngannou"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Care este termenul pentru scorul zero la tenis?",
    correct_answer: "Love",
    incorrect_answers: ["Nil", "Zero", "Nimic"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce jucator NBA a murit intr-un accident de elicopter in 2020?",
    correct_answer: "Kobe Bryant",
    incorrect_answers: ["Shaquille O'Neal", "Michael Jordan", "Wilt Chamberlain"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Ce natiune a gazduit primele Jocuri Olimpice de iarna in 1924?",
    correct_answer: "Franta",
    incorrect_answers: ["Elvetia", "Norvegia", "Canada"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce sport se practica pe un velodrom?",
    correct_answer: "Ciclism",
    incorrect_answers: ["Inot", "Alergare", "Patinaj"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Cine a castigat titlul de MVP la Super Bowl in 2021 (Tampa Bay)?",
    correct_answer: "Tom Brady",
    incorrect_answers: ["Patrick Mahomes", "Rob Gronkowski", "Aaron Rodgers"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Cati jucatori sunt pe teren in fotbalul australian (Australian Rules)?",
    correct_answer: "18",
    incorrect_answers: ["15", "11", "13"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce sport foloseste un 'birdie'?",
    correct_answer: "Badminton",
    incorrect_answers: ["Tenis", "Squash", "Pickleball"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce oras este casa echipei NFL Cowboys?",
    correct_answer: "Dallas",
    incorrect_answers: ["Houston", "Austin", "San Antonio"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Ce jucatoare de tenis a completat un Golden Slam in 1988?",
    correct_answer: "Steffi Graf",
    incorrect_answers: ["Serena Williams", "Martina Navratilova", "Monica Seles"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce sport implica sarituri, barna si paralele?",
    correct_answer: "Gimnastica",
    incorrect_answers: ["Patinaj artistic", "Sariture in apa", "Majorete"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Din ce tara este Lewis Hamilton?",
    correct_answer: "Marea Britanie",
    incorrect_answers: ["SUA", "Australia", "Canada"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Care este distanta la Kentucky Derby?",
    correct_answer: "1.25 mile",
    incorrect_answers: ["1 mila", "1.5 mile", "2 mile"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Care este numarul maxim de crose permis intr-o geanta de golf?",
    correct_answer: "14",
    incorrect_answers: ["12", "15", "10"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Cine este antrenorul echipei Manchester City (2023)?",
    correct_answer: "Pep Guardiola",
    incorrect_answers: ["Jurgen Klopp", "Jose Mourinho", "Alex Ferguson"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a fost prima sportiva care a aparut pe o cutie de cereale Wheaties?",
    correct_answer: "Babe Didrikson Zaharias",
    incorrect_answers: ["Mary Lou Retton", "Serena Williams", "Wilma Rudolph"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Cate puncte valoreaza o aruncare libera la baschet?",
    correct_answer: "1",
    incorrect_answers: ["2", "3", "0.5"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce echipa are cele mai multe titluri Champions League?",
    correct_answer: "Real Madrid",
    incorrect_answers: ["AC Milan", "Liverpool", "Bayern Munchen"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Care este sportul national al Canadei (vara)?",
    correct_answer: "Lacrosse",
    incorrect_answers: ["Hochei pe gheata", "Baseball", "Fotbal"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Care stil de inot este cel mai lent?",
    correct_answer: "Bras",
    incorrect_answers: ["Liber", "Fluture", "Spate"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "In ce oras are loc US Open (Tenis)?",
    correct_answer: "New York",
    incorrect_answers: ["Los Angeles", "Miami", "Chicago"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a fost primul jucator care a alergat 2000 de yarzi intr-un sezon NFL?",
    correct_answer: "O.J. Simpson",
    incorrect_answers: ["Eric Dickerson", "Barry Sanders", "Walter Payton"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Care este echivalentul unui 'home run' in cricket?",
    correct_answer: "Sase (Six)",
    incorrect_answers: ["Patru", "Cinci", "Zece"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce echipa MLB a castigat cele mai multe titluri World Series?",
    correct_answer: "New York Yankees",
    incorrect_answers: ["St. Louis Cardinals", "Boston Red Sox", "LA Dodgers"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Carui ciclist i s-au retras 7 titluri din Turul Frantei?",
    correct_answer: "Lance Armstrong",
    incorrect_answers: ["Alberto Contador", "Jan Ullrich", "Floyd Landis"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Cate sferturi sunt intr-un joc de fotbal american?",
    correct_answer: "4",
    incorrect_answers: ["2", "3", "5"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce tara gazduieste Cupa Melbourne?",
    correct_answer: "Australia",
    incorrect_answers: ["Marea Britanie", "SUA", "Franta"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Care este singurul sport care a fost jucat pe luna?",
    correct_answer: "Golf",
    incorrect_answers: ["Tenis", "Baseball", "Fotbal"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Cine este cunoscut ca 'Iron Mike'?",
    correct_answer: "Mike Tyson",
    incorrect_answers: ["Evander Holyfield", "Lennox Lewis", "Muhammad Ali"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Ce arta martiala este un sport olimpic?",
    correct_answer: "Judo",
    incorrect_answers: ["Kung Fu", "Jiu-Jitsu", "Kickboxing"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a marcat golul 'Mana lui Dumnezeu'?",
    correct_answer: "Diego Maradona",
    incorrect_answers: ["Lionel Messi", "Pelé", "Ronaldo Nazario"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Ce sport are loc intr-un bazin?",
    correct_answer: "Polo pe apa",
    incorrect_answers: ["Handbal", "Volei", "Baschet"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Cate tururi are cursa Indy 500?",
    correct_answer: "200",
    incorrect_answers: ["500", "100", "250"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Care este numele stadionului unde joaca Boston Red Sox?",
    correct_answer: "Fenway Park",
    incorrect_answers: ["Yankee Stadium", "Wrigley Field", "Citi Field"],
  },
  // --- STIINTA (LOT 1 - MIXT) ---
  {
    category: 17,
    type: "multiple",
    difficulty: "easy",
    question: "Care este simbolul chimic pentru Oxigen?",
    correct_answer: "O",
    incorrect_answers: ["Ox", "Oxg", "On"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "medium",
    question: "Care este 'uzina de energie' a celulei?",
    correct_answer: "Mitocondria",
    incorrect_answers: ["Nucleul", "Ribozomul", "Cloroplastul"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "easy",
    question: "Care planeta este cea mai apropiata de Soare?",
    correct_answer: "Mercur",
    incorrect_answers: ["Venus", "Marte", "Pamant"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "hard",
    question: "Care este cea mai rara grupa de sange la oameni?",
    correct_answer: "AB Negativ",
    incorrect_answers: ["0 Pozitiv", "B Negativ", "A Pozitiv"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "medium",
    question: "Ce gaz absorb plantele din atmosfera?",
    correct_answer: "Dioxid de carbon",
    incorrect_answers: ["Oxigen", "Azot", "Hidrogen"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "easy",
    question: "Cate oase sunt in corpul uman adult?",
    correct_answer: "206",
    incorrect_answers: ["200", "210", "208"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "medium",
    question: "La ce temperatura fierbe apa (Celsius)?",
    correct_answer: "100",
    incorrect_answers: ["90", "110", "120"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a dezvoltat Teoria Relativitatii Generale?",
    correct_answer: "Albert Einstein",
    incorrect_answers: ["Isaac Newton", "Niels Bohr", "Stephen Hawking"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "easy",
    question: "Care este cel mai mare organ al corpului uman?",
    correct_answer: "Pielea",
    incorrect_answers: ["Ficatul", "Inima", "Plamanii"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "medium",
    question: "Ce element are numarul atomic 1?",
    correct_answer: "Hidrogen",
    incorrect_answers: ["Heliu", "Litiu", "Carbon"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "easy",
    question: "Ce parte a plantei realizeaza fotosinteza?",
    correct_answer: "Frunza",
    incorrect_answers: ["Radacina", "Tulpina", "Floarea"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "hard",
    question: "Care este cea mai dura substanta naturala de pe Pamant?",
    correct_answer: "Diamantul",
    incorrect_answers: ["Corindonul", "Topazul", "Cuartul"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "medium",
    question: "Care este viteza luminii (aprox)?",
    correct_answer: "300.000 km/s",
    incorrect_answers: ["150.000 km/s", "1.000 km/s", "3.000 km/s"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "easy",
    question: "Ce grupa de sange este donator universal?",
    correct_answer: "0 Negativ",
    incorrect_answers: ["AB Pozitiv", "A Pozitiv", "B Negativ"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "hard",
    question: "Care planeta are Marea Pata Rosie?",
    correct_answer: "Jupiter",
    incorrect_answers: ["Marte", "Saturn", "Neptun"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "medium",
    question: "Care este gazul principal din aerul pe care il respiram?",
    correct_answer: "Azot",
    incorrect_answers: ["Oxigen", "Dioxid de carbon", "Hidrogen"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "easy",
    question: "Ce atrage obiectele spre centrul Pamantului?",
    correct_answer: "Gravitatia",
    incorrect_answers: ["Magnetismul", "Frecarea", "Inertia"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "medium",
    question: "Cate inimi are o caracatita?",
    correct_answer: "3",
    incorrect_answers: ["1", "2", "4"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a descoperit Penicilina?",
    correct_answer: "Alexander Fleming",
    incorrect_answers: ["Louis Pasteur", "Marie Curie", "Joseph Lister"],
  },
  {
    category: 17,
    type: "multiple",
    difficulty: "easy",
    question: "Care planeta este cunoscuta ca Planeta Rosie?",
    correct_answer: "Marte",
    incorrect_answers: ["Venus", "Jupiter", "Mercur"],
  },
