export const CUSTOM_QUESTIONS_EN = [
  {
    category: 9, // General Knowledge
    type: "multiple",
    difficulty: "easy",
    question: "What is the capital of France?",
    correct_answer: "Paris",
    incorrect_answers: ["London", "Berlin", "Madrid"],
  },
  {
    category: 11, // Movies
    type: "multiple",
    difficulty: "medium",
    question: "Who directed 'Inception'?",
    correct_answer: "Christopher Nolan",
    incorrect_answers: ["Steven Spielberg", "Quentin Tarantino", "Martin Scorsese"],
  },
  // --- GENERAL KNOWLEDGE (BATCH 1) ---
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which animal is known as the 'Ship of the Desert'?",
    correct_answer: "Camel",
    incorrect_answers: ["Horse", "Elephant", "Zebra"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "How many days are there in a leap year?",
    correct_answer: "366",
    incorrect_answers: ["365", "364", "360"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the Greek God of War?",
    correct_answer: "Ares",
    incorrect_answers: ["Zeus", "Apollo", "Hermes"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which country gifted the Statue of Liberty to the USA?",
    correct_answer: "France",
    incorrect_answers: ["United Kingdom", "Spain", "Italy"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "What is the rarest blood type?",
    correct_answer: "AB-Negative",
    incorrect_answers: ["O-Positive", "B-Negative", "A-Positive"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the largest ocean in the world?",
    correct_answer: "Pacific Ocean",
    incorrect_answers: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which chemical element has the symbol 'K'?",
    correct_answer: "Potassium",
    incorrect_answers: ["Krypton", "Kevinium", "Kalphon"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Who painted the Mona Lisa?",
    correct_answer: "Leonardo da Vinci",
    incorrect_answers: ["Pablo Picasso", "Vincent van Gogh", "Michelangelo"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Which planet has the most moons?",
    correct_answer: "Saturn",
    incorrect_answers: ["Jupiter", "Uranus", "Neptune"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the fear of spiders called?",
    correct_answer: "Arachnophobia",
    incorrect_answers: ["Acrophobia", "Claustrophobia", "Hydrophobia"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which fruit is associated with Isaac Newton?",
    correct_answer: "Apple",
    incorrect_answers: ["Pear", "Orange", "Banana"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which company owns Bugatti, Lamborghini, and Audi?",
    correct_answer: "Volkswagen",
    incorrect_answers: ["Toyota", "General Motors", "Ford"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the main ingredient in guacamole?",
    correct_answer: "Avocado",
    incorrect_answers: ["Tomato", "Onion", "Pepper"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "How many hearts does an octopus have?",
    correct_answer: "3",
    incorrect_answers: ["1", "2", "4"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "In what year did the Berlin Wall fall?",
    correct_answer: "1989",
    incorrect_answers: ["1987", "1991", "1990"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What does the 'www' stand for in a website browser?",
    correct_answer: "World Wide Web",
    incorrect_answers: ["World Web Wide", "Wide World Web", "Web World Wide"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which famous physicist wrote 'A Brief History of Time'?",
    correct_answer: "Stephen Hawking",
    incorrect_answers: ["Albert Einstein", "Isaac Newton", "Niels Bohr"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "What is the smallest bone in the human body?",
    correct_answer: "Stapes (Ear bone)",
    incorrect_answers: ["Phalanges", "Femur", "Tibia"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What comes after the letter 'F' in the alphabet?",
    correct_answer: "G",
    incorrect_answers: ["E", "H", "I"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the hardest natural substance on Earth?",
    correct_answer: "Diamond",
    incorrect_answers: ["Gold", "Iron", "Platinum"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which Disney character is a flying elephant?",
    correct_answer: "Dumbo",
    incorrect_answers: ["Bambi", "Simba", "Pluto"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which city is known as the 'Big Apple'?",
    correct_answer: "New York City",
    incorrect_answers: ["Los Angeles", "Chicago", "Miami"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Which element has the atomic number 1?",
    correct_answer: "Hydrogen",
    incorrect_answers: ["Helium", "Oxygen", "Carbon"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What color is a sapphire?",
    correct_answer: "Blue",
    incorrect_answers: ["Red", "Green", "Yellow"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which country invented pizza?",
    correct_answer: "Italy",
    incorrect_answers: ["USA", "France", "China"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "What year did the first man land on the moon?",
    correct_answer: "1969",
    incorrect_answers: ["1965", "1972", "1959"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "How many legs does a spider have?",
    correct_answer: "8",
    incorrect_answers: ["6", "4", "10"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the national flower of Japan?",
    correct_answer: "Cherry Blossom",
    incorrect_answers: ["Rose", "Lily", "Tulip"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Who wrote '1984'?",
    correct_answer: "George Orwell",
    incorrect_answers: ["Aldous Huxley", "Ernest Hemingway", "F. Scott Fitzgerald"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the frozen form of water called?",
    correct_answer: "Ice",
    incorrect_answers: ["Steam", "Liquid", "Gas"],
  },
  // --- GENERAL KNOWLEDGE (BATCH 2 - EXTENDED) ---
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which language has the most native speakers worldwide?",
    correct_answer: "Mandarin Chinese",
    incorrect_answers: ["English", "Spanish", "Hindi"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the main color of the Netflix logo?",
    correct_answer: "Red",
    incorrect_answers: ["Blue", "Green", "Black"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Who was the first woman to win a Nobel Prize?",
    correct_answer: "Marie Curie",
    incorrect_answers: ["Mother Teresa", "Jane Addams", "Rosalind Franklin"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which brand uses the slogan 'Just Do It'?",
    correct_answer: "Nike",
    incorrect_answers: ["Adidas", "Puma", "Reebok"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which bird is known for imitating human speech?",
    correct_answer: "Parrot",
    incorrect_answers: ["Eagle", "Owl", "Penguin"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the tallest mammal in the world?",
    correct_answer: "Giraffe",
    incorrect_answers: ["Elephant", "Blue Whale", "Horse"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Which chess piece can only move diagonally?",
    correct_answer: "Bishop",
    incorrect_answers: ["Rook", "Knight", "Pawn"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "How many sides does a triangle have?",
    correct_answer: "3",
    incorrect_answers: ["4", "5", "2"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which planet in our solar system is the hottest?",
    correct_answer: "Venus",
    incorrect_answers: ["Mercury", "Mars", "Jupiter"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the toy cowboy in 'Toy Story'?",
    correct_answer: "Woody",
    incorrect_answers: ["Buzz", "Andy", "Jessie"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "In which year did the Titanic movie come out?",
    correct_answer: "1997",
    incorrect_answers: ["1995", "1999", "2000"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which country produces the most coffee in the world?",
    correct_answer: "Brazil",
    incorrect_answers: ["Colombia", "Vietnam", "Ethiopia"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the opposite of 'Hot'?",
    correct_answer: "Cold",
    incorrect_answers: ["Warm", "Luke-warm", "Spicy"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Who founded Microsoft?",
    correct_answer: "Bill Gates",
    incorrect_answers: ["Steve Jobs", "Elon Musk", "Mark Zuckerberg"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the currency of the United Kingdom?",
    correct_answer: "Pound Sterling",
    incorrect_answers: ["Euro", "Dollar", "Yen"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which animal is the symbol of the WWF?",
    correct_answer: "Panda",
    incorrect_answers: ["Tiger", "Lion", "Bear"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "How many stars are on the flag of China?",
    correct_answer: "5",
    incorrect_answers: ["4", "6", "1"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which organ pumps blood around the human body?",
    correct_answer: "Heart",
    incorrect_answers: ["Brain", "Lungs", "Liver"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the primary color of a banana?",
    correct_answer: "Yellow",
    incorrect_answers: ["Red", "Green", "Blue"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which famous ship sank in 1912?",
    correct_answer: "Titanic",
    incorrect_answers: ["Lusitania", "Olympic", "Britannic"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Which gas makes up the majority of the Earth's atmosphere?",
    correct_answer: "Nitrogen",
    incorrect_answers: ["Oxygen", "Carbon Dioxide", "Hydrogen"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What do bees produce?",
    correct_answer: "Honey",
    incorrect_answers: ["Milk", "Silk", "Wool"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Who is the author of 'Harry Potter'?",
    correct_answer: "J.K. Rowling",
    incorrect_answers: ["J.R.R. Tolkien", "George R.R. Martin", "Stephen King"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "What represents the letter 'O' in the Morse code?",
    correct_answer: "---",
    incorrect_answers: ["...", ".-", "-.-"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which country has the largest population?",
    correct_answer: "India",
    incorrect_answers: ["China", "USA", "Russia"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which season comes after Summer?",
    correct_answer: "Autumn",
    incorrect_answers: ["Winter", "Spring", "Monsoon"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What does the 'E' stand for in 'Email'?",
    correct_answer: "Electronic",
    incorrect_answers: ["Electric", "Engine", "Easy"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Which artist cut off his own ear?",
    correct_answer: "Vincent van Gogh",
    incorrect_answers: ["Pablo Picasso", "Claude Monet", "Salvador Dali"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the fastest land animal?",
    correct_answer: "Cheetah",
    incorrect_answers: ["Lion", "Horse", "Tiger"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "How many players are in a standard soccer team?",
    correct_answer: "11",
    incorrect_answers: ["10", "12", "9"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "What is the capital of Canada?",
    correct_answer: "Ottawa",
    incorrect_answers: ["Toronto", "Montreal", "Vancouver"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which fairy tale character slept for 100 years?",
    correct_answer: "Sleeping Beauty",
    incorrect_answers: ["Cinderella", "Snow White", "Rapunzel"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which car manufacturer has a horse in its logo?",
    correct_answer: "Ferrari",
    incorrect_answers: ["Lamborghini", "Audi", "BMW"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Who was the first person to step on the Moon?",
    correct_answer: "Neil Armstrong",
    incorrect_answers: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the largest internal organ in the human body?",
    correct_answer: "Liver",
    incorrect_answers: ["Heart", "Lungs", "Stomach"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What kind of food is Penne?",
    correct_answer: "Pasta",
    incorrect_answers: ["Bread", "Cheese", "Meat"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which country is famous for tulips and windmills?",
    correct_answer: "Netherlands",
    incorrect_answers: ["Germany", "Switzerland", "Belgium"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "What is the chemical symbol for Gold?",
    correct_answer: "Au",
    incorrect_answers: ["Ag", "Go", "Gd"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "How many hours are there in a day?",
    correct_answer: "24",
    incorrect_answers: ["12", "48", "36"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Who painted the ceiling of the Sistine Chapel?",
    correct_answer: "Michelangelo",
    incorrect_answers: ["Leonardo da Vinci", "Raphael", "Donatello"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Which war was fought between the North and South regions in the United States?",
    correct_answer: "The Civil War",
    incorrect_answers: ["Revolutionary War", "World War I", "Vietnam War"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which animal is the largest living reptile?",
    correct_answer: "Saltwater Crocodile",
    incorrect_answers: ["Komodo Dragon", "Python", "Alligator"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the fictional city where Batman lives?",
    correct_answer: "Gotham City",
    incorrect_answers: ["Metropolis", "Star City", "Central City"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "How many stripes are on the US flag?",
    correct_answer: "13",
    incorrect_answers: ["50", "10", "12"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which soft drink was originally green?",
    correct_answer: "None (It's a myth, but often attributed to Mountain Dew)",
    incorrect_answers: ["Coca Cola", "Pepsi", "Sprite"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the hardest rock?",
    correct_answer: "Diamond",
    incorrect_answers: ["Granite", "Marble", "Quartz"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the main ingredient in chocolate?",
    correct_answer: "Cocoa",
    incorrect_answers: ["Milk", "Sugar", "Vanilla"],
  },
  // --- MOVIES (BATCH 1 - MIXED) ---
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named Jack Sparrow?",
    correct_answer: "Pirates of the Caribbean",
    incorrect_answers: ["Harry Potter", "Lord of the Rings", "Indiana Jones"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "In 'The Matrix', which pill does Neo take?",
    correct_answer: "Red",
    incorrect_answers: ["Blue", "Green", "Yellow"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Who played Iron Man in the Marvel Cinematic Universe?",
    correct_answer: "Robert Downey Jr.",
    incorrect_answers: ["Chris Evans", "Chris Hemsworth", "Mark Ruffalo"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie won the Oscar for Best Picture in 1994?",
    correct_answer: "Schindler's List",
    incorrect_answers: ["Pulp Fiction", "Forrest Gump", "The Shawshank Redemption"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the kingdom in 'Frozen'?",
    correct_answer: "Arendelle",
    incorrect_answers: ["Genovia", "Aldovia", "Florin"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which dinosaur is the main antagonist in 'Jurassic Park'?",
    correct_answer: "T-Rex",
    incorrect_answers: ["Velociraptor", "Triceratops", "Brachiosaurus"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Who directed the movie 'Avatar'?",
    correct_answer: "James Cameron",
    incorrect_answers: ["Steven Spielberg", "George Lucas", "Ridley Scott"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "In 'Pulp Fiction', what do they call a Quarter Pounder with Cheese in Paris?",
    correct_answer: "Royale with Cheese",
    incorrect_answers: ["Le Big Mac", "French Burger", "Cheese Royale"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What kind of animal is Baloo in 'The Jungle Book'?",
    correct_answer: "Bear",
    incorrect_answers: ["Tiger", "Wolf", "Panther"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which actor played the Joker in 'The Dark Knight'?",
    correct_answer: "Heath Ledger",
    incorrect_answers: ["Joaquin Phoenix", "Jared Leto", "Jack Nicholson"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Who lives in a pineapple under the sea?",
    correct_answer: "SpongeBob SquarePants",
    incorrect_answers: ["Patrick Star", "Squidward", "Mr. Krabs"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "What is the name of the computer in '2001: A Space Odyssey'?",
    correct_answer: "HAL 9000",
    incorrect_answers: ["Skynet", "Jarvis", "Deep Blue"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the quote 'Here's looking at you, kid'?",
    correct_answer: "Casablanca",
    incorrect_answers: ["Gone with the Wind", "Citizen Kane", "The Godfather"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "In 'Harry Potter', what is the name of Harry's owl?",
    correct_answer: "Hedwig",
    incorrect_answers: ["Scabbers", "Crookshanks", "Fang"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Who played the character of Jack Dawson in 'Titanic'?",
    correct_answer: "Leonardo DiCaprio",
    incorrect_answers: ["Brad Pitt", "Matt Damon", "Johnny Depp"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which film was the first to be released in the Marvel Cinematic Universe?",
    correct_answer: "Iron Man",
    incorrect_answers: ["The Incredible Hulk", "Captain America", "Thor"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the ogre in 'Shrek'?",
    correct_answer: "Shrek",
    incorrect_answers: ["Donkey", "Fiona", "Farquaad"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "In 'Star Wars', who is Luke Skywalker's father?",
    correct_answer: "Darth Vader",
    incorrect_answers: ["Obi-Wan Kenobi", "Palpatine", "Yoda"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie is set in the fictional country of Wakanda?",
    correct_answer: "Black Panther",
    incorrect_answers: ["Coming to America", "District 9", "Hotel Rwanda"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which superhero is known as the 'Man of Steel'?",
    correct_answer: "Superman",
    incorrect_answers: ["Batman", "Iron Man", "Thor"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which actor famously performed his own stunts in 'Mission: Impossible'?",
    correct_answer: "Tom Cruise",
    incorrect_answers: ["Keanu Reeves", "Daniel Craig", "Jason Statham"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "What is the name of the sled in 'Citizen Kane'?",
    correct_answer: "Rosebud",
    incorrect_answers: ["Snowbird", "Thunder", "Lightning"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "In 'Finding Nemo', what kind of fish is Nemo?",
    correct_answer: "Clownfish",
    incorrect_answers: ["Goldfish", "Shark", "Pufferfish"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features a theme park with cloned dinosaurs?",
    correct_answer: "Jurassic Park",
    incorrect_answers: ["King Kong", "Godzilla", "Planet of the Apes"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'Psycho'?",
    correct_answer: "Alfred Hitchcock",
    incorrect_answers: ["Stanley Kubrick", "Francis Ford Coppola", "Martin Scorsese"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which character says 'I am Groot'?",
    correct_answer: "Groot",
    incorrect_answers: ["Rocket", "Star-Lord", "Drax"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "What color is the lightsaber of Mace Windu in 'Star Wars'?",
    correct_answer: "Purple",
    incorrect_answers: ["Green", "Blue", "Red"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie features the song 'My Heart Will Go On'?",
    correct_answer: "Titanic",
    incorrect_answers: ["The Bodyguard", "Ghost", "Pretty Woman"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Who is Batman's loyal butler?",
    correct_answer: "Alfred",
    incorrect_answers: ["Robin", "Gordon", "Lucius"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie tells the story of Mozart?",
    correct_answer: "Amadeus",
    incorrect_answers: ["Immortal Beloved", "Shine", "The Pianist"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "What is the highest-grossing film of all time (as of 2023)?",
    correct_answer: "Avatar",
    incorrect_answers: ["Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which Disney princess has a glass slipper?",
    correct_answer: "Cinderella",
    incorrect_answers: ["Snow White", "Belle", "Aurora"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Who played the character of Forrest Gump?",
    correct_answer: "Tom Hanks",
    incorrect_answers: ["Harrison Ford", "Bill Murray", "Kevin Costner"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "In 'The Silence of the Lambs', what is the name of the serial killer?",
    correct_answer: "Hannibal Lecter",
    incorrect_answers: ["Norman Bates", "Jack Torrance", "Patrick Bateman"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What fictional city is the home of Superman?",
    correct_answer: "Metropolis",
    incorrect_answers: ["Gotham", "Star City", "Smallville"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie involves a DeLorean time machine?",
    correct_answer: "Back to the Future",
    incorrect_answers: ["Blade Runner", "Total Recall", "The Terminator"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'The Godfather'?",
    correct_answer: "Francis Ford Coppola",
    incorrect_answers: ["Martin Scorsese", "Sergio Leone", "Brian De Palma"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which animal is Simba in 'The Lion King'?",
    correct_answer: "Lion",
    incorrect_answers: ["Tiger", "Cheetah", "Leopard"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features a volleyball named Wilson?",
    correct_answer: "Cast Away",
    incorrect_answers: ["The Terminal", "Apollo 13", "Saving Private Ryan"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "What is the name of the hotel in 'The Shining'?",
    correct_answer: "Overlook Hotel",
    incorrect_answers: ["Bates Motel", "Grand Budapest Hotel", "Hotel California"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Who is the villain in '101 Dalmatians'?",
    correct_answer: "Cruella de Vil",
    incorrect_answers: ["Ursula", "Maleficent", "Evil Queen"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which actress played Katniss Everdeen in 'The Hunger Games'?",
    correct_answer: "Jennifer Lawrence",
    incorrect_answers: ["Emma Watson", "Shailene Woodley", "Kristen Stewart"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which film won the first ever Academy Award for Best Picture?",
    correct_answer: "Wings",
    incorrect_answers: ["Sunrise", "Metropolis", "The Jazz Singer"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which toy comes to life in 'Toy Story'?",
    correct_answer: "All of them",
    incorrect_answers: ["Only Woody", "Only Buzz", "None"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the quote 'You can't handle the truth!'?",
    correct_answer: "A Few Good Men",
    incorrect_answers: ["Top Gun", "Jerry Maguire", "Rain Man"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "What is the real name of The Rock?",
    correct_answer: "Dwayne Johnson",
    incorrect_answers: ["Steve Austin", "John Cena", "Dave Bautista"],
  },
  // --- MOVIES (BATCH 2 - EXTENDED) ---
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the dog in 'The Wizard of Oz'?",
    correct_answer: "Toto",
    incorrect_answers: ["Lassie", "Buddy", "Rex"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "In 'Fight Club', what is the first rule of Fight Club?",
    correct_answer: "You do not talk about Fight Club",
    incorrect_answers: ["You do not fight without a shirt", "Two guys to a fight", "Fights go on as long as they have to"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie won the Best Picture Oscar in 2020 (the first non-English language film to do so)?",
    correct_answer: "Parasite",
    incorrect_answers: ["Roma", "1917", "Jojo Rabbit"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which actor plays Wolverine in the X-Men movies?",
    correct_answer: "Hugh Jackman",
    incorrect_answers: ["Christian Bale", "Tom Hardy", "Ben Affleck"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the island in 'Jurassic Park'?",
    correct_answer: "Isla Nublar",
    incorrect_answers: ["Isla Sorna", "Isla Mujeres", "Isla Grande"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'E.T. the Extra-Terrestrial'?",
    correct_answer: "Steven Spielberg",
    incorrect_answers: ["George Lucas", "James Cameron", "Tim Burton"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the snowman in 'Frozen'?",
    correct_answer: "Olaf",
    incorrect_answers: ["Sven", "Kristoff", "Hans"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the character 'Donnie Darko'?",
    correct_answer: "Donnie Darko",
    incorrect_answers: ["Nightcrawler", "Prisoners", "Zodiac"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "In 'The Matrix', what is the name of the ship Morpheus captains?",
    correct_answer: "Nebuchadnezzar",
    incorrect_answers: ["Icarus", "Prometheus", "Nostromo"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Who is the main villain in 'Star Wars: A New Hope'?",
    correct_answer: "Darth Vader",
    incorrect_answers: ["Emperor Palpatine", "Kylo Ren", "Darth Maul"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which film features the line 'I see dead people'?",
    correct_answer: "The Sixth Sense",
    incorrect_answers: ["The Others", "Poltergeist", "Ghostbusters"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "What is the name of the demon in 'The Exorcist'?",
    correct_answer: "Pazuzu",
    incorrect_answers: ["Beelzebub", "Azazel", "Lucifer"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which superhero is Peter Parker?",
    correct_answer: "Spider-Man",
    incorrect_answers: ["Superman", "Batman", "Flash"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Who played the character of Neo in 'The Matrix'?",
    correct_answer: "Keanu Reeves",
    incorrect_answers: ["Will Smith", "Brad Pitt", "Tom Cruise"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie is based on a Stephen King novel about a clown?",
    correct_answer: "It",
    incorrect_answers: ["The Shining", "Carrie", "Misery"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the lion in 'The Chronicles of Narnia'?",
    correct_answer: "Aslan",
    incorrect_answers: ["Simba", "Mufasa", "Scar"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features a character named 'The Dude'?",
    correct_answer: "The Big Lebowski",
    incorrect_answers: ["Fargo", "No Country for Old Men", "Burn After Reading"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'Blade Runner' (1982)?",
    correct_answer: "Ridley Scott",
    incorrect_answers: ["Denis Villeneuve", "James Cameron", "George Miller"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie is about a theme park with dinosaurs?",
    correct_answer: "Jurassic Park",
    incorrect_answers: ["King Kong", "Godzilla", "The Land Before Time"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the ring in 'The Lord of the Rings'?",
    correct_answer: "The One Ring",
    incorrect_answers: ["The Ring of Power", "The Precious Ring", "The Golden Ring"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "In 'Goodfellas', what is the name of Ray Liotta's character?",
    correct_answer: "Henry Hill",
    incorrect_answers: ["Tommy DeVito", "Jimmy Conway", "Paul Cicero"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named 'Buzz Lightyear'?",
    correct_answer: "Toy Story",
    incorrect_answers: ["Cars", "Monsters, Inc.", "The Incredibles"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Who played the Joker in the 1989 'Batman' movie?",
    correct_answer: "Jack Nicholson",
    incorrect_answers: ["Heath Ledger", "Jared Leto", "Cesar Romero"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie features the quote 'You talking to me?'?",
    correct_answer: "Taxi Driver",
    incorrect_answers: ["Raging Bull", "Goodfellas", "Mean Streets"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the fairy in 'Peter Pan'?",
    correct_answer: "Tinker Bell",
    incorrect_answers: ["Silvermist", "Fawn", "Iridessa"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie is set on the planet Pandora?",
    correct_answer: "Avatar",
    incorrect_answers: ["Star Trek", "Guardians of the Galaxy", "Alien"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'Inception'?",
    correct_answer: "Christopher Nolan",
    incorrect_answers: ["Quentin Tarantino", "David Fincher", "Wes Anderson"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named 'Shrek'?",
    correct_answer: "Shrek",
    incorrect_answers: ["Ice Age", "Madagascar", "Kung Fu Panda"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the hotel in 'Pretty Woman'?",
    correct_answer: "Regent Beverly Wilshire",
    incorrect_answers: ["The Plaza", "The Ritz", "The Waldorf Astoria"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie won the Best Picture Oscar in 2017 (after a mistake)?",
    correct_answer: "Moonlight",
    incorrect_answers: ["La La Land", "Arrival", "Manchester by the Sea"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Who is the main character in 'The Lion King'?",
    correct_answer: "Simba",
    incorrect_answers: ["Mufasa", "Nala", "Scar"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the song 'Eye of the Tiger'?",
    correct_answer: "Rocky III",
    incorrect_answers: ["The Karate Kid", "Top Gun", "Flashdance"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who played the character of Hannibal Lecter in 'The Silence of the Lambs'?",
    correct_answer: "Anthony Hopkins",
    incorrect_answers: ["Brian Cox", "Mads Mikkelsen", "Jeremy Irons"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named 'Dory'?",
    correct_answer: "Finding Nemo",
    incorrect_answers: ["The Little Mermaid", "Shark Tale", "Moana"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the spaceship in 'Alien'?",
    correct_answer: "Nostromo",
    incorrect_answers: ["Sulaco", "Prometheus", "Covenant"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'The Grand Budapest Hotel'?",
    correct_answer: "Wes Anderson",
    incorrect_answers: ["Paul Thomas Anderson", "Coen Brothers", "Spike Jonze"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named 'Elsa'?",
    correct_answer: "Frozen",
    incorrect_answers: ["Tangled", "Brave", "Moana"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the quote 'Frankly, my dear, I don't give a damn'?",
    correct_answer: "Gone with the Wind",
    incorrect_answers: ["Casablanca", "Citizen Kane", "The Wizard of Oz"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who played the character of Tyler Durden in 'Fight Club'?",
    correct_answer: "Brad Pitt",
    incorrect_answers: ["Edward Norton", "Jared Leto", "Matt Damon"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named 'Lightning McQueen'?",
    correct_answer: "Cars",
    incorrect_answers: ["Planes", "Turbo", "Herbie"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the song 'Unchained Melody'?",
    correct_answer: "Ghost",
    incorrect_answers: ["Dirty Dancing", "Pretty Woman", "Top Gun"],
  },
