export const CUSTOM_QUESTIONS_EN = [
  {
    category: 9, // General Knowledge
    type: "multiple",
    difficulty: "easy",
    question: "What is the capital of France?",
    correct_answer: "Paris",
    incorrect_answers: ["London", "Berlin", "Madrid"],
  },
  {
    category: 11, // Movies
    type: "multiple",
    difficulty: "medium",
    question: "Who directed 'Inception'?",
    correct_answer: "Christopher Nolan",
    incorrect_answers: ["Steven Spielberg", "Quentin Tarantino", "Martin Scorsese"],
  },
  // --- GENERAL KNOWLEDGE (BATCH 1) ---
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which animal is known as the 'Ship of the Desert'?",
    correct_answer: "Camel",
    incorrect_answers: ["Horse", "Elephant", "Zebra"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "How many days are there in a leap year?",
    correct_answer: "366",
    incorrect_answers: ["365", "364", "360"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the Greek God of War?",
    correct_answer: "Ares",
    incorrect_answers: ["Zeus", "Apollo", "Hermes"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which country gifted the Statue of Liberty to the USA?",
    correct_answer: "France",
    incorrect_answers: ["United Kingdom", "Spain", "Italy"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "What is the rarest blood type?",
    correct_answer: "AB-Negative",
    incorrect_answers: ["O-Positive", "B-Negative", "A-Positive"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the largest ocean in the world?",
    correct_answer: "Pacific Ocean",
    incorrect_answers: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which chemical element has the symbol 'K'?",
    correct_answer: "Potassium",
    incorrect_answers: ["Krypton", "Kevinium", "Kalphon"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Who painted the Mona Lisa?",
    correct_answer: "Leonardo da Vinci",
    incorrect_answers: ["Pablo Picasso", "Vincent van Gogh", "Michelangelo"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Which planet has the most moons?",
    correct_answer: "Saturn",
    incorrect_answers: ["Jupiter", "Uranus", "Neptune"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the fear of spiders called?",
    correct_answer: "Arachnophobia",
    incorrect_answers: ["Acrophobia", "Claustrophobia", "Hydrophobia"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which fruit is associated with Isaac Newton?",
    correct_answer: "Apple",
    incorrect_answers: ["Pear", "Orange", "Banana"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which company owns Bugatti, Lamborghini, and Audi?",
    correct_answer: "Volkswagen",
    incorrect_answers: ["Toyota", "General Motors", "Ford"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the main ingredient in guacamole?",
    correct_answer: "Avocado",
    incorrect_answers: ["Tomato", "Onion", "Pepper"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "How many hearts does an octopus have?",
    correct_answer: "3",
    incorrect_answers: ["1", "2", "4"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "In what year did the Berlin Wall fall?",
    correct_answer: "1989",
    incorrect_answers: ["1987", "1991", "1990"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What does the 'www' stand for in a website browser?",
    correct_answer: "World Wide Web",
    incorrect_answers: ["World Web Wide", "Wide World Web", "Web World Wide"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which famous physicist wrote 'A Brief History of Time'?",
    correct_answer: "Stephen Hawking",
    incorrect_answers: ["Albert Einstein", "Isaac Newton", "Niels Bohr"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "What is the smallest bone in the human body?",
    correct_answer: "Stapes (Ear bone)",
    incorrect_answers: ["Phalanges", "Femur", "Tibia"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What comes after the letter 'F' in the alphabet?",
    correct_answer: "G",
    incorrect_answers: ["E", "H", "I"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the hardest natural substance on Earth?",
    correct_answer: "Diamond",
    incorrect_answers: ["Gold", "Iron", "Platinum"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which Disney character is a flying elephant?",
    correct_answer: "Dumbo",
    incorrect_answers: ["Bambi", "Simba", "Pluto"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which city is known as the 'Big Apple'?",
    correct_answer: "New York City",
    incorrect_answers: ["Los Angeles", "Chicago", "Miami"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Which element has the atomic number 1?",
    correct_answer: "Hydrogen",
    incorrect_answers: ["Helium", "Oxygen", "Carbon"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What color is a sapphire?",
    correct_answer: "Blue",
    incorrect_answers: ["Red", "Green", "Yellow"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which country invented pizza?",
    correct_answer: "Italy",
    incorrect_answers: ["USA", "France", "China"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "What year did the first man land on the moon?",
    correct_answer: "1969",
    incorrect_answers: ["1965", "1972", "1959"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "How many legs does a spider have?",
    correct_answer: "8",
    incorrect_answers: ["6", "4", "10"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the national flower of Japan?",
    correct_answer: "Cherry Blossom",
    incorrect_answers: ["Rose", "Lily", "Tulip"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Who wrote '1984'?",
    correct_answer: "George Orwell",
    incorrect_answers: ["Aldous Huxley", "Ernest Hemingway", "F. Scott Fitzgerald"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the frozen form of water called?",
    correct_answer: "Ice",
    incorrect_answers: ["Steam", "Liquid", "Gas"],
  },
  // --- GENERAL KNOWLEDGE (BATCH 2 - EXTENDED) ---
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which language has the most native speakers worldwide?",
    correct_answer: "Mandarin Chinese",
    incorrect_answers: ["English", "Spanish", "Hindi"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the main color of the Netflix logo?",
    correct_answer: "Red",
    incorrect_answers: ["Blue", "Green", "Black"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Who was the first woman to win a Nobel Prize?",
    correct_answer: "Marie Curie",
    incorrect_answers: ["Mother Teresa", "Jane Addams", "Rosalind Franklin"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which brand uses the slogan 'Just Do It'?",
    correct_answer: "Nike",
    incorrect_answers: ["Adidas", "Puma", "Reebok"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which bird is known for imitating human speech?",
    correct_answer: "Parrot",
    incorrect_answers: ["Eagle", "Owl", "Penguin"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the tallest mammal in the world?",
    correct_answer: "Giraffe",
    incorrect_answers: ["Elephant", "Blue Whale", "Horse"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Which chess piece can only move diagonally?",
    correct_answer: "Bishop",
    incorrect_answers: ["Rook", "Knight", "Pawn"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "How many sides does a triangle have?",
    correct_answer: "3",
    incorrect_answers: ["4", "5", "2"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which planet in our solar system is the hottest?",
    correct_answer: "Venus",
    incorrect_answers: ["Mercury", "Mars", "Jupiter"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the toy cowboy in 'Toy Story'?",
    correct_answer: "Woody",
    incorrect_answers: ["Buzz", "Andy", "Jessie"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "In which year did the Titanic movie come out?",
    correct_answer: "1997",
    incorrect_answers: ["1995", "1999", "2000"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which country produces the most coffee in the world?",
    correct_answer: "Brazil",
    incorrect_answers: ["Colombia", "Vietnam", "Ethiopia"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the opposite of 'Hot'?",
    correct_answer: "Cold",
    incorrect_answers: ["Warm", "Luke-warm", "Spicy"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Who founded Microsoft?",
    correct_answer: "Bill Gates",
    incorrect_answers: ["Steve Jobs", "Elon Musk", "Mark Zuckerberg"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the currency of the United Kingdom?",
    correct_answer: "Pound Sterling",
    incorrect_answers: ["Euro", "Dollar", "Yen"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which animal is the symbol of the WWF?",
    correct_answer: "Panda",
    incorrect_answers: ["Tiger", "Lion", "Bear"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "How many stars are on the flag of China?",
    correct_answer: "5",
    incorrect_answers: ["4", "6", "1"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which organ pumps blood around the human body?",
    correct_answer: "Heart",
    incorrect_answers: ["Brain", "Lungs", "Liver"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the primary color of a banana?",
    correct_answer: "Yellow",
    incorrect_answers: ["Red", "Green", "Blue"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which famous ship sank in 1912?",
    correct_answer: "Titanic",
    incorrect_answers: ["Lusitania", "Olympic", "Britannic"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Which gas makes up the majority of the Earth's atmosphere?",
    correct_answer: "Nitrogen",
    incorrect_answers: ["Oxygen", "Carbon Dioxide", "Hydrogen"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What do bees produce?",
    correct_answer: "Honey",
    incorrect_answers: ["Milk", "Silk", "Wool"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Who is the author of 'Harry Potter'?",
    correct_answer: "J.K. Rowling",
    incorrect_answers: ["J.R.R. Tolkien", "George R.R. Martin", "Stephen King"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "What represents the letter 'O' in the Morse code?",
    correct_answer: "---",
    incorrect_answers: ["...", ".-", "-.-"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which country has the largest population?",
    correct_answer: "India",
    incorrect_answers: ["China", "USA", "Russia"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which season comes after Summer?",
    correct_answer: "Autumn",
    incorrect_answers: ["Winter", "Spring", "Monsoon"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What does the 'E' stand for in 'Email'?",
    correct_answer: "Electronic",
    incorrect_answers: ["Electric", "Engine", "Easy"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Which artist cut off his own ear?",
    correct_answer: "Vincent van Gogh",
    incorrect_answers: ["Pablo Picasso", "Claude Monet", "Salvador Dali"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the fastest land animal?",
    correct_answer: "Cheetah",
    incorrect_answers: ["Lion", "Horse", "Tiger"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "How many players are in a standard soccer team?",
    correct_answer: "11",
    incorrect_answers: ["10", "12", "9"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "What is the capital of Canada?",
    correct_answer: "Ottawa",
    incorrect_answers: ["Toronto", "Montreal", "Vancouver"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which fairy tale character slept for 100 years?",
    correct_answer: "Sleeping Beauty",
    incorrect_answers: ["Cinderella", "Snow White", "Rapunzel"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which car manufacturer has a horse in its logo?",
    correct_answer: "Ferrari",
    incorrect_answers: ["Lamborghini", "Audi", "BMW"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Who was the first person to step on the Moon?",
    correct_answer: "Neil Armstrong",
    incorrect_answers: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the largest internal organ in the human body?",
    correct_answer: "Liver",
    incorrect_answers: ["Heart", "Lungs", "Stomach"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What kind of food is Penne?",
    correct_answer: "Pasta",
    incorrect_answers: ["Bread", "Cheese", "Meat"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which country is famous for tulips and windmills?",
    correct_answer: "Netherlands",
    incorrect_answers: ["Germany", "Switzerland", "Belgium"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "What is the chemical symbol for Gold?",
    correct_answer: "Au",
    incorrect_answers: ["Ag", "Go", "Gd"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "How many hours are there in a day?",
    correct_answer: "24",
    incorrect_answers: ["12", "48", "36"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Who painted the ceiling of the Sistine Chapel?",
    correct_answer: "Michelangelo",
    incorrect_answers: ["Leonardo da Vinci", "Raphael", "Donatello"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "Which war was fought between the North and South regions in the United States?",
    correct_answer: "The Civil War",
    incorrect_answers: ["Revolutionary War", "World War I", "Vietnam War"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "Which animal is the largest living reptile?",
    correct_answer: "Saltwater Crocodile",
    incorrect_answers: ["Komodo Dragon", "Python", "Alligator"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the fictional city where Batman lives?",
    correct_answer: "Gotham City",
    incorrect_answers: ["Metropolis", "Star City", "Central City"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "hard",
    question: "How many stripes are on the US flag?",
    correct_answer: "13",
    incorrect_answers: ["50", "10", "12"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "Which soft drink was originally green?",
    correct_answer: "None (It's a myth, but often attributed to Mountain Dew)",
    incorrect_answers: ["Coca Cola", "Pepsi", "Sprite"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "medium",
    question: "What is the hardest rock?",
    correct_answer: "Diamond",
    incorrect_answers: ["Granite", "Marble", "Quartz"],
  },
  {
    category: 9,
    type: "multiple",
    difficulty: "easy",
    question: "What is the main ingredient in chocolate?",
    correct_answer: "Cocoa",
    incorrect_answers: ["Milk", "Sugar", "Vanilla"],
  },
  // --- MOVIES (BATCH 1 - MIXED) ---
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named Jack Sparrow?",
    correct_answer: "Pirates of the Caribbean",
    incorrect_answers: ["Harry Potter", "Lord of the Rings", "Indiana Jones"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "In 'The Matrix', which pill does Neo take?",
    correct_answer: "Red",
    incorrect_answers: ["Blue", "Green", "Yellow"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Who played Iron Man in the Marvel Cinematic Universe?",
    correct_answer: "Robert Downey Jr.",
    incorrect_answers: ["Chris Evans", "Chris Hemsworth", "Mark Ruffalo"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie won the Oscar for Best Picture in 1994?",
    correct_answer: "Schindler's List",
    incorrect_answers: ["Pulp Fiction", "Forrest Gump", "The Shawshank Redemption"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the kingdom in 'Frozen'?",
    correct_answer: "Arendelle",
    incorrect_answers: ["Genovia", "Aldovia", "Florin"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which dinosaur is the main antagonist in 'Jurassic Park'?",
    correct_answer: "T-Rex",
    incorrect_answers: ["Velociraptor", "Triceratops", "Brachiosaurus"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Who directed the movie 'Avatar'?",
    correct_answer: "James Cameron",
    incorrect_answers: ["Steven Spielberg", "George Lucas", "Ridley Scott"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "In 'Pulp Fiction', what do they call a Quarter Pounder with Cheese in Paris?",
    correct_answer: "Royale with Cheese",
    incorrect_answers: ["Le Big Mac", "French Burger", "Cheese Royale"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What kind of animal is Baloo in 'The Jungle Book'?",
    correct_answer: "Bear",
    incorrect_answers: ["Tiger", "Wolf", "Panther"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which actor played the Joker in 'The Dark Knight'?",
    correct_answer: "Heath Ledger",
    incorrect_answers: ["Joaquin Phoenix", "Jared Leto", "Jack Nicholson"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Who lives in a pineapple under the sea?",
    correct_answer: "SpongeBob SquarePants",
    incorrect_answers: ["Patrick Star", "Squidward", "Mr. Krabs"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "What is the name of the computer in '2001: A Space Odyssey'?",
    correct_answer: "HAL 9000",
    incorrect_answers: ["Skynet", "Jarvis", "Deep Blue"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the quote 'Here's looking at you, kid'?",
    correct_answer: "Casablanca",
    incorrect_answers: ["Gone with the Wind", "Citizen Kane", "The Godfather"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "In 'Harry Potter', what is the name of Harry's owl?",
    correct_answer: "Hedwig",
    incorrect_answers: ["Scabbers", "Crookshanks", "Fang"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Who played the character of Jack Dawson in 'Titanic'?",
    correct_answer: "Leonardo DiCaprio",
    incorrect_answers: ["Brad Pitt", "Matt Damon", "Johnny Depp"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which film was the first to be released in the Marvel Cinematic Universe?",
    correct_answer: "Iron Man",
    incorrect_answers: ["The Incredible Hulk", "Captain America", "Thor"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the ogre in 'Shrek'?",
    correct_answer: "Shrek",
    incorrect_answers: ["Donkey", "Fiona", "Farquaad"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "In 'Star Wars', who is Luke Skywalker's father?",
    correct_answer: "Darth Vader",
    incorrect_answers: ["Obi-Wan Kenobi", "Palpatine", "Yoda"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie is set in the fictional country of Wakanda?",
    correct_answer: "Black Panther",
    incorrect_answers: ["Coming to America", "District 9", "Hotel Rwanda"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which superhero is known as the 'Man of Steel'?",
    correct_answer: "Superman",
    incorrect_answers: ["Batman", "Iron Man", "Thor"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which actor famously performed his own stunts in 'Mission: Impossible'?",
    correct_answer: "Tom Cruise",
    incorrect_answers: ["Keanu Reeves", "Daniel Craig", "Jason Statham"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "What is the name of the sled in 'Citizen Kane'?",
    correct_answer: "Rosebud",
    incorrect_answers: ["Snowbird", "Thunder", "Lightning"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "In 'Finding Nemo', what kind of fish is Nemo?",
    correct_answer: "Clownfish",
    incorrect_answers: ["Goldfish", "Shark", "Pufferfish"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features a theme park with cloned dinosaurs?",
    correct_answer: "Jurassic Park",
    incorrect_answers: ["King Kong", "Godzilla", "Planet of the Apes"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'Psycho'?",
    correct_answer: "Alfred Hitchcock",
    incorrect_answers: ["Stanley Kubrick", "Francis Ford Coppola", "Martin Scorsese"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which character says 'I am Groot'?",
    correct_answer: "Groot",
    incorrect_answers: ["Rocket", "Star-Lord", "Drax"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "What color is the lightsaber of Mace Windu in 'Star Wars'?",
    correct_answer: "Purple",
    incorrect_answers: ["Green", "Blue", "Red"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie features the song 'My Heart Will Go On'?",
    correct_answer: "Titanic",
    incorrect_answers: ["The Bodyguard", "Ghost", "Pretty Woman"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Who is Batman's loyal butler?",
    correct_answer: "Alfred",
    incorrect_answers: ["Robin", "Gordon", "Lucius"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie tells the story of Mozart?",
    correct_answer: "Amadeus",
    incorrect_answers: ["Immortal Beloved", "Shine", "The Pianist"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "What is the highest-grossing film of all time (as of 2023)?",
    correct_answer: "Avatar",
    incorrect_answers: ["Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which Disney princess has a glass slipper?",
    correct_answer: "Cinderella",
    incorrect_answers: ["Snow White", "Belle", "Aurora"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Who played the character of Forrest Gump?",
    correct_answer: "Tom Hanks",
    incorrect_answers: ["Harrison Ford", "Bill Murray", "Kevin Costner"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "In 'The Silence of the Lambs', what is the name of the serial killer?",
    correct_answer: "Hannibal Lecter",
    incorrect_answers: ["Norman Bates", "Jack Torrance", "Patrick Bateman"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What fictional city is the home of Superman?",
    correct_answer: "Metropolis",
    incorrect_answers: ["Gotham", "Star City", "Smallville"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie involves a DeLorean time machine?",
    correct_answer: "Back to the Future",
    incorrect_answers: ["Blade Runner", "Total Recall", "The Terminator"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'The Godfather'?",
    correct_answer: "Francis Ford Coppola",
    incorrect_answers: ["Martin Scorsese", "Sergio Leone", "Brian De Palma"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which animal is Simba in 'The Lion King'?",
    correct_answer: "Lion",
    incorrect_answers: ["Tiger", "Cheetah", "Leopard"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features a volleyball named Wilson?",
    correct_answer: "Cast Away",
    incorrect_answers: ["The Terminal", "Apollo 13", "Saving Private Ryan"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "What is the name of the hotel in 'The Shining'?",
    correct_answer: "Overlook Hotel",
    incorrect_answers: ["Bates Motel", "Grand Budapest Hotel", "Hotel California"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Who is the villain in '101 Dalmatians'?",
    correct_answer: "Cruella de Vil",
    incorrect_answers: ["Ursula", "Maleficent", "Evil Queen"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which actress played Katniss Everdeen in 'The Hunger Games'?",
    correct_answer: "Jennifer Lawrence",
    incorrect_answers: ["Emma Watson", "Shailene Woodley", "Kristen Stewart"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which film won the first ever Academy Award for Best Picture?",
    correct_answer: "Wings",
    incorrect_answers: ["Sunrise", "Metropolis", "The Jazz Singer"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which toy comes to life in 'Toy Story'?",
    correct_answer: "All of them",
    incorrect_answers: ["Only Woody", "Only Buzz", "None"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the quote 'You can't handle the truth!'?",
    correct_answer: "A Few Good Men",
    incorrect_answers: ["Top Gun", "Jerry Maguire", "Rain Man"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "What is the real name of The Rock?",
    correct_answer: "Dwayne Johnson",
    incorrect_answers: ["Steve Austin", "John Cena", "Dave Bautista"],
  },
  // --- MOVIES (BATCH 2 - EXTENDED) ---
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the dog in 'The Wizard of Oz'?",
    correct_answer: "Toto",
    incorrect_answers: ["Lassie", "Buddy", "Rex"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "In 'Fight Club', what is the first rule of Fight Club?",
    correct_answer: "You do not talk about Fight Club",
    incorrect_answers: ["You do not fight without a shirt", "Two guys to a fight", "Fights go on as long as they have to"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie won the Best Picture Oscar in 2020 (the first non-English language film to do so)?",
    correct_answer: "Parasite",
    incorrect_answers: ["Roma", "1917", "Jojo Rabbit"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which actor plays Wolverine in the X-Men movies?",
    correct_answer: "Hugh Jackman",
    incorrect_answers: ["Christian Bale", "Tom Hardy", "Ben Affleck"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the island in 'Jurassic Park'?",
    correct_answer: "Isla Nublar",
    incorrect_answers: ["Isla Sorna", "Isla Mujeres", "Isla Grande"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'E.T. the Extra-Terrestrial'?",
    correct_answer: "Steven Spielberg",
    incorrect_answers: ["George Lucas", "James Cameron", "Tim Burton"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the snowman in 'Frozen'?",
    correct_answer: "Olaf",
    incorrect_answers: ["Sven", "Kristoff", "Hans"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the character 'Donnie Darko'?",
    correct_answer: "Donnie Darko",
    incorrect_answers: ["Nightcrawler", "Prisoners", "Zodiac"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "In 'The Matrix', what is the name of the ship Morpheus captains?",
    correct_answer: "Nebuchadnezzar",
    incorrect_answers: ["Icarus", "Prometheus", "Nostromo"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Who is the main villain in 'Star Wars: A New Hope'?",
    correct_answer: "Darth Vader",
    incorrect_answers: ["Emperor Palpatine", "Kylo Ren", "Darth Maul"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which film features the line 'I see dead people'?",
    correct_answer: "The Sixth Sense",
    incorrect_answers: ["The Others", "Poltergeist", "Ghostbusters"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "What is the name of the demon in 'The Exorcist'?",
    correct_answer: "Pazuzu",
    incorrect_answers: ["Beelzebub", "Azazel", "Lucifer"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which superhero is Peter Parker?",
    correct_answer: "Spider-Man",
    incorrect_answers: ["Superman", "Batman", "Flash"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Who played the character of Neo in 'The Matrix'?",
    correct_answer: "Keanu Reeves",
    incorrect_answers: ["Will Smith", "Brad Pitt", "Tom Cruise"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie is based on a Stephen King novel about a clown?",
    correct_answer: "It",
    incorrect_answers: ["The Shining", "Carrie", "Misery"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the lion in 'The Chronicles of Narnia'?",
    correct_answer: "Aslan",
    incorrect_answers: ["Simba", "Mufasa", "Scar"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features a character named 'The Dude'?",
    correct_answer: "The Big Lebowski",
    incorrect_answers: ["Fargo", "No Country for Old Men", "Burn After Reading"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'Blade Runner' (1982)?",
    correct_answer: "Ridley Scott",
    incorrect_answers: ["Denis Villeneuve", "James Cameron", "George Miller"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie is about a theme park with dinosaurs?",
    correct_answer: "Jurassic Park",
    incorrect_answers: ["King Kong", "Godzilla", "The Land Before Time"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the ring in 'The Lord of the Rings'?",
    correct_answer: "The One Ring",
    incorrect_answers: ["The Ring of Power", "The Precious Ring", "The Golden Ring"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "In 'Goodfellas', what is the name of Ray Liotta's character?",
    correct_answer: "Henry Hill",
    incorrect_answers: ["Tommy DeVito", "Jimmy Conway", "Paul Cicero"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named 'Buzz Lightyear'?",
    correct_answer: "Toy Story",
    incorrect_answers: ["Cars", "Monsters, Inc.", "The Incredibles"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Who played the Joker in the 1989 'Batman' movie?",
    correct_answer: "Jack Nicholson",
    incorrect_answers: ["Heath Ledger", "Jared Leto", "Cesar Romero"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie features the quote 'You talking to me?'?",
    correct_answer: "Taxi Driver",
    incorrect_answers: ["Raging Bull", "Goodfellas", "Mean Streets"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the fairy in 'Peter Pan'?",
    correct_answer: "Tinker Bell",
    incorrect_answers: ["Silvermist", "Fawn", "Iridessa"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie is set on the planet Pandora?",
    correct_answer: "Avatar",
    incorrect_answers: ["Star Trek", "Guardians of the Galaxy", "Alien"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'Inception'?",
    correct_answer: "Christopher Nolan",
    incorrect_answers: ["Quentin Tarantino", "David Fincher", "Wes Anderson"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named 'Shrek'?",
    correct_answer: "Shrek",
    incorrect_answers: ["Ice Age", "Madagascar", "Kung Fu Panda"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the hotel in 'Pretty Woman'?",
    correct_answer: "Regent Beverly Wilshire",
    incorrect_answers: ["The Plaza", "The Ritz", "The Waldorf Astoria"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Which movie won the Best Picture Oscar in 2017 (after a mistake)?",
    correct_answer: "Moonlight",
    incorrect_answers: ["La La Land", "Arrival", "Manchester by the Sea"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Who is the main character in 'The Lion King'?",
    correct_answer: "Simba",
    incorrect_answers: ["Mufasa", "Nala", "Scar"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the song 'Eye of the Tiger'?",
    correct_answer: "Rocky III",
    incorrect_answers: ["The Karate Kid", "Top Gun", "Flashdance"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who played the character of Hannibal Lecter in 'The Silence of the Lambs'?",
    correct_answer: "Anthony Hopkins",
    incorrect_answers: ["Brian Cox", "Mads Mikkelsen", "Jeremy Irons"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named 'Dory'?",
    correct_answer: "Finding Nemo",
    incorrect_answers: ["The Little Mermaid", "Shark Tale", "Moana"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the spaceship in 'Alien'?",
    correct_answer: "Nostromo",
    incorrect_answers: ["Sulaco", "Prometheus", "Covenant"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'The Grand Budapest Hotel'?",
    correct_answer: "Wes Anderson",
    incorrect_answers: ["Paul Thomas Anderson", "Coen Brothers", "Spike Jonze"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named 'Elsa'?",
    correct_answer: "Frozen",
    incorrect_answers: ["Tangled", "Brave", "Moana"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the quote 'Frankly, my dear, I don't give a damn'?",
    correct_answer: "Gone with the Wind",
    incorrect_answers: ["Casablanca", "Citizen Kane", "The Wizard of Oz"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who played the character of Tyler Durden in 'Fight Club'?",
    correct_answer: "Brad Pitt",
    incorrect_answers: ["Edward Norton", "Jared Leto", "Matt Damon"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named 'Lightning McQueen'?",
    correct_answer: "Cars",
    incorrect_answers: ["Planes", "Turbo", "Herbie"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the song 'Unchained Melody'?",
    correct_answer: "Ghost",
    incorrect_answers: ["Dirty Dancing", "Pretty Woman", "Top Gun"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "easy",
    question: "Which movie features a character named 'Po'?",
    correct_answer: "Kung Fu Panda",
    incorrect_answers: ["Mulan", "Raya and the Last Dragon", "Turning Red"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "Which movie features the song 'Stayin' Alive'?",
    correct_answer: "Saturday Night Fever",
    incorrect_answers: ["Grease", "Footloose", "Flashdance"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Who directed 'Pulp Fiction'?",
    correct_answer: "Quentin Tarantino",
    incorrect_answers: ["Guy Ritchie", "Robert Rodriguez", "Coen Brothers"],
  },
  // --- MUSIC (BATCH 1 - MIXED) ---
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which singer is known as the 'Queen of Pop'?",
    correct_answer: "Madonna",
    incorrect_answers: ["Lady Gaga", "Beyoncé", "Britney Spears"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Who wrote the song 'Bohemian Rhapsody'?",
    correct_answer: "Freddie Mercury",
    incorrect_answers: ["Elton John", "David Bowie", "Paul McCartney"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which band performed 'Dancing Queen'?",
    correct_answer: "ABBA",
    incorrect_answers: ["The Beatles", "Bee Gees", "Fleetwood Mac"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "What is the real name of Lady Gaga?",
    correct_answer: "Stefani Germanotta",
    incorrect_answers: ["Robyn Fenty", "Katheryn Hudson", "Alecia Moore"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "How many strings does a standard guitar have?",
    correct_answer: "6",
    incorrect_answers: ["4", "5", "7"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which Canadian artist sang 'Baby'?",
    correct_answer: "Justin Bieber",
    incorrect_answers: ["Drake", "The Weeknd", "Shawn Mendes"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Who is the lead singer of the band Coldplay?",
    correct_answer: "Chris Martin",
    incorrect_answers: ["Thom Yorke", "Bono", "Adam Levine"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "In which year did Elvis Presley die?",
    correct_answer: "1977",
    incorrect_answers: ["1975", "1980", "1969"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which pop star fans are called 'Swifties'?",
    correct_answer: "Taylor Swift",
    incorrect_answers: ["Ariana Grande", "Katy Perry", "Selena Gomez"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which rapper released the album 'The Marshall Mathers LP'?",
    correct_answer: "Eminem",
    incorrect_answers: ["50 Cent", "Jay-Z", "Dr. Dre"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which classical composer was deaf in his later years?",
    correct_answer: "Ludwig van Beethoven",
    incorrect_answers: ["Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Frederic Chopin"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who sang 'I Will Always Love You' in the movie 'The Bodyguard'?",
    correct_answer: "Whitney Houston",
    incorrect_answers: ["Mariah Carey", "Celine Dion", "Aretha Franklin"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which grunge band was Kurt Cobain the frontman of?",
    correct_answer: "Nirvana",
    incorrect_answers: ["Pearl Jam", "Soundgarden", "Alice in Chains"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "What instrument does Lizzo play?",
    correct_answer: "Flute",
    incorrect_answers: ["Violin", "Piano", "Saxophone"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which album is the best-selling of all time?",
    correct_answer: "Thriller (Michael Jackson)",
    incorrect_answers: ["Back in Black (AC/DC)", "The Dark Side of the Moon (Pink Floyd)", "Rumours (Fleetwood Mac)"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Who is known as the 'Godfather of Soul'?",
    correct_answer: "James Brown",
    incorrect_answers: ["Ray Charles", "Otis Redding", "Marvin Gaye"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which British girl group had a hit with 'Wannabe'?",
    correct_answer: "Spice Girls",
    incorrect_answers: ["Little Mix", "Destiny's Child", "The Pussycat Dolls"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which country is the band U2 from?",
    correct_answer: "Ireland",
    incorrect_answers: ["United Kingdom", "USA", "Australia"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Who was the original drummer for The Beatles?",
    correct_answer: "Pete Best",
    incorrect_answers: ["Ringo Starr", "Keith Moon", "John Bonham"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who sings the hit song 'Hello'?",
    correct_answer: "Adele",
    incorrect_answers: ["Sia", "Rihanna", "Amy Winehouse"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which artist is known as 'Prince'?",
    correct_answer: "Prince Rogers Nelson",
    incorrect_answers: ["Michael Jackson", "David Bowie", "Elton John"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "How many keys are on a standard piano?",
    correct_answer: "88",
    incorrect_answers: ["64", "76", "100"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which song begins with 'Is this the real life? Is this just fantasy?'?",
    correct_answer: "Bohemian Rhapsody",
    incorrect_answers: ["Stairway to Heaven", "Imagine", "Hotel California"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Who is the lead singer of The Rolling Stones?",
    correct_answer: "Mick Jagger",
    incorrect_answers: ["Keith Richards", "Robert Plant", "Steven Tyler"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "What was the first music video played on MTV?",
    correct_answer: "Video Killed the Radio Star",
    incorrect_answers: ["Thriller", "Take on Me", "Billie Jean"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which singer is famous for the 'Moonwalk'?",
    correct_answer: "Michael Jackson",
    incorrect_answers: ["Usher", "Justin Timberlake", "Bruno Mars"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which famous festival took place in 1969?",
    correct_answer: "Woodstock",
    incorrect_answers: ["Glastonbury", "Coachella", "Lollapalooza"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Who composed 'The Four Seasons'?",
    correct_answer: "Antonio Vivaldi",
    incorrect_answers: ["Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who is Beyonce married to?",
    correct_answer: "Jay-Z",
    incorrect_answers: ["Kanye West", "Drake", "P. Diddy"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "What genre of music is Bob Marley famous for?",
    correct_answer: "Reggae",
    incorrect_answers: ["Jazz", "Blues", "Rap"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which Pink Floyd album features a prism on the cover?",
    correct_answer: "The Dark Side of the Moon",
    incorrect_answers: ["The Wall", "Wish You Were Here", "Animals"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who recorded the hit 'Shape of You'?",
    correct_answer: "Ed Sheeran",
    incorrect_answers: ["Sam Smith", "Harry Styles", "Lewis Capaldi"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which band has a logo of a mouth with a tongue sticking out?",
    correct_answer: "The Rolling Stones",
    incorrect_answers: ["KISS", "The Beatles", "Led Zeppelin"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "What is the name of the scale with five notes per octave?",
    correct_answer: "Pentatonic scale",
    incorrect_answers: ["Chromatic scale", "Diatonic scale", "Minor scale"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which country music legend sang 'Jolene'?",
    correct_answer: "Dolly Parton",
    incorrect_answers: ["Reba McEntire", "Shania Twain", "Carrie Underwood"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Who is the 'Rocket Man'?",
    correct_answer: "Elton John",
    incorrect_answers: ["David Bowie", "Freddie Mercury", "Billy Joel"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which rapper was shot and killed in Las Vegas in 1996?",
    correct_answer: "Tupac Shakur",
    incorrect_answers: ["Notorious B.I.G.", "Eazy-E", "XXXtentacion"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which musical instrument has black and white keys?",
    correct_answer: "Piano",
    incorrect_answers: ["Guitar", "Violin", "Trumpet"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "What was the name of the group Beyoncé was in before going solo?",
    correct_answer: "Destiny's Child",
    incorrect_answers: ["TLC", "En Vogue", "The Supremes"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Who wrote the lyrics for the musical 'Hamilton'?",
    correct_answer: "Lin-Manuel Miranda",
    incorrect_answers: ["Andrew Lloyd Webber", "Stephen Sondheim", "Tim Rice"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who sang 'Single Ladies (Put a Ring on It)'?",
    correct_answer: "Beyoncé",
    incorrect_answers: ["Rihanna", "Alicia Keys", "Jennifer Lopez"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which band released 'Smells Like Teen Spirit'?",
    correct_answer: "Nirvana",
    incorrect_answers: ["Pearl Jam", "Foo Fighters", "Green Day"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "What is the lowest male singing voice?",
    correct_answer: "Bass",
    incorrect_answers: ["Tenor", "Baritone", "Alto"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who released the hit song 'Blinding Lights'?",
    correct_answer: "The Weeknd",
    incorrect_answers: ["Drake", "Post Malone", "Travis Scott"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which instrument is associated with Louis Armstrong?",
    correct_answer: "Trumpet",
    incorrect_answers: ["Saxophone", "Piano", "Drums"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which year did The Beatles break up?",
    correct_answer: "1970",
    incorrect_answers: ["1969", "1971", "1968"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "What nationality is Justin Bieber?",
    correct_answer: "Canadian",
    incorrect_answers: ["American", "British", "Australian"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Who sings 'Rolling in the Deep'?",
    correct_answer: "Adele",
    incorrect_answers: ["Katy Perry", "Taylor Swift", "Lady Gaga"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Who is known as the 'Empress of the Blues'?",
    correct_answer: "Bessie Smith",
    incorrect_answers: ["Billie Holiday", "Ella Fitzgerald", "Aretha Franklin"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which band sings 'Yellow Submarine'?",
    correct_answer: "The Beatles",
    incorrect_answers: ["The Rolling Stones", "The Who", "The Kinks"],
  },
  // --- MUSIC (BATCH 2 - EXTENDED) ---
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which singer is known as the 'Material Girl'?",
    correct_answer: "Madonna",
    incorrect_answers: ["Cyndi Lauper", "Cher", "Kylie Minogue"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Who is the lead singer of the band Guns N' Roses?",
    correct_answer: "Axl Rose",
    incorrect_answers: ["Slash", "Steven Tyler", "Jon Bon Jovi"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which classical composer wrote 'The Magic Flute'?",
    correct_answer: "Wolfgang Amadeus Mozart",
    incorrect_answers: ["Beethoven", "Bach", "Haydn"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which song features the dance move 'Gangnam Style'?",
    correct_answer: "Gangnam Style",
    incorrect_answers: ["Gentleman", "Despacito", "Macarena"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which band sang 'Hotel California'?",
    correct_answer: "Eagles",
    incorrect_answers: ["Lynyrd Skynyrd", "Fleetwood Mac", "The Doors"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "What is the real name of the DJ Avicii?",
    correct_answer: "Tim Bergling",
    incorrect_answers: ["Calvin Harris", "David Guetta", "Martin Garrix"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who sings 'Bad Guy'?",
    correct_answer: "Billie Eilish",
    incorrect_answers: ["Lorde", "Dua Lipa", "Halsey"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which artist released the album 'Purple Rain'?",
    correct_answer: "Prince",
    incorrect_answers: ["Michael Jackson", "Stevie Wonder", "Lionel Richie"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which heavy metal band released the 'Black Album'?",
    correct_answer: "Metallica",
    incorrect_answers: ["Iron Maiden", "Megadeth", "Slayer"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which Spice Girl was known as 'Posh Spice'?",
    correct_answer: "Victoria Beckham",
    incorrect_answers: ["Mel B", "Geri Halliwell", "Emma Bunton"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Who sang 'Respect'?",
    correct_answer: "Aretha Franklin",
    incorrect_answers: ["Diana Ross", "Tina Turner", "Etta James"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which band was originally called 'Kara's Flowers'?",
    correct_answer: "Maroon 5",
    incorrect_answers: ["Coldplay", "Imagine Dragons", "OneRepublic"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who is Miley Cyrus's father?",
    correct_answer: "Billy Ray Cyrus",
    incorrect_answers: ["Johnny Cash", "Willie Nelson", "Garth Brooks"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which song begins with the lyrics 'Is this the real life?'",
    correct_answer: "Bohemian Rhapsody",
    incorrect_answers: ["Somebody to Love", "We Are the Champions", "Don't Stop Me Now"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Who is the drummer for the band Blink-182?",
    correct_answer: "Travis Barker",
    incorrect_answers: ["Dave Grohl", "Tre Cool", "Taylor Hawkins"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who sang 'Umbrella'?",
    correct_answer: "Rihanna",
    incorrect_answers: ["Beyoncé", "Ciara", "Katy Perry"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which instrument did Jimi Hendrix play?",
    correct_answer: "Guitar",
    incorrect_answers: ["Drums", "Bass", "Piano"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which rapper founded the record label 'OVO Sound'?",
    correct_answer: "Drake",
    incorrect_answers: ["Kanye West", "Jay-Z", "Lil Wayne"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who is known as the 'Piano Man'?",
    correct_answer: "Billy Joel",
    incorrect_answers: ["Elton John", "Stevie Wonder", "Ray Charles"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which British singer died at the age of 27 in 2011?",
    correct_answer: "Amy Winehouse",
    incorrect_answers: ["Janis Joplin", "Whitney Houston", "Aaliyah"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which symphony is known as the 'Choral' symphony?",
    correct_answer: "Beethoven's 9th",
    incorrect_answers: ["Mozart's 40th", "Mahler's 5th", "Schubert's 8th"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which band sings 'We Will Rock You'?",
    correct_answer: "Queen",
    incorrect_answers: ["AC/DC", "KISS", "Bon Jovi"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "What was the first name of the composer Bach?",
    correct_answer: "Johann",
    incorrect_answers: ["Ludwig", "Wolfgang", "Franz"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which artist has a fan base called the 'Little Monsters'?",
    correct_answer: "Lady Gaga",
    incorrect_answers: ["Katy Perry", "Nicki Minaj", "Miley Cyrus"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who sang 'Thriller'?",
    correct_answer: "Michael Jackson",
    incorrect_answers: ["Prince", "Stevie Wonder", "Lionel Richie"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which band is famous for the song 'Sweet Child O' Mine'?",
    correct_answer: "Guns N' Roses",
    incorrect_answers: ["Aerosmith", "Def Leppard", "Motley Crue"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which rapper is known as 'Slim Shady'?",
    correct_answer: "Eminem",
    incorrect_answers: ["Dr. Dre", "Snoop Dogg", "Ice Cube"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who sings 'Shake It Off'?",
    correct_answer: "Taylor Swift",
    incorrect_answers: ["Selena Gomez", "Demi Lovato", "Ariana Grande"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Who was the lead singer of The Police?",
    correct_answer: "Sting",
    incorrect_answers: ["Bono", "Phil Collins", "Rod Stewart"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which country won the Eurovision Song Contest in 1974 with ABBA?",
    correct_answer: "Sweden",
    incorrect_answers: ["Norway", "Denmark", "Finland"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "What instrument has 4 strings and is often used in Hawaii?",
    correct_answer: "Ukulele",
    incorrect_answers: ["Banjo", "Guitar", "Violin"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which song was a hit for Britney Spears in 1998?",
    correct_answer: "Baby One More Time",
    incorrect_answers: ["Toxic", "Oops!... I Did It Again", "Crazy"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Which band released the album 'The Joshua Tree'?",
    correct_answer: "U2",
    incorrect_answers: ["R.E.M.", "Radiohead", "The Cure"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who sings 'Firework'?",
    correct_answer: "Katy Perry",
    incorrect_answers: ["Rihanna", "Lady Gaga", "Sia"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Who is the lead singer of Aerosmith?",
    correct_answer: "Steven Tyler",
    incorrect_answers: ["Mick Jagger", "Robert Plant", "Ozzy Osbourne"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "What is the name of the lead singer of System of a Down?",
    correct_answer: "Serj Tankian",
    incorrect_answers: ["Daron Malakian", "Chester Bennington", "Jonathan Davis"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Which singer is known as 'The King of Rock and Roll'?",
    correct_answer: "Elvis Presley",
    incorrect_answers: ["Chuck Berry", "Little Richard", "Buddy Holly"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "medium",
    question: "Which band sang 'Wonderwall'?",
    correct_answer: "Oasis",
    incorrect_answers: ["Blur", "The Verve", "Radiohead"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "hard",
    question: "Who wrote 'Hallelujah'?",
    correct_answer: "Leonard Cohen",
    incorrect_answers: ["Bob Dylan", "Paul Simon", "Jeff Buckley"],
  },
  {
    category: 12,
    type: "multiple",
    difficulty: "easy",
    question: "Who sings 'Thinking Out Loud'?",
    correct_answer: "Ed Sheeran",
    incorrect_answers: ["Sam Smith", "John Legend", "Bruno Mars"],
  },
  // --- SPORTS (BATCH 1 - MIXED) ---
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Which sport is played at Wimbledon?",
    correct_answer: "Tennis",
    incorrect_answers: ["Golf", "Cricket", "Soccer"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "How long is a marathon?",
    correct_answer: "42.195 km",
    incorrect_answers: ["40 km", "50 km", "21 km"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "In which sport would you perform a slam dunk?",
    correct_answer: "Basketball",
    incorrect_answers: ["Volleyball", "Tennis", "Baseball"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Which country won the first FIFA World Cup in 1930?",
    correct_answer: "Uruguay",
    incorrect_answers: ["Brazil", "Argentina", "Italy"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Who holds the record for the most Olympic gold medals?",
    correct_answer: "Michael Phelps",
    incorrect_answers: ["Usain Bolt", "Carl Lewis", "Mark Spitz"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "What is the national sport of Japan?",
    correct_answer: "Sumo Wrestling",
    incorrect_answers: ["Karate", "Judo", "Baseball"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Which NBA team is known as the 'Lakers'?",
    correct_answer: "Los Angeles",
    incorrect_answers: ["Chicago", "New York", "Boston"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Who won the Formula 1 World Championship in 2021?",
    correct_answer: "Max Verstappen",
    incorrect_answers: ["Lewis Hamilton", "Sebastian Vettel", "Valtteri Bottas"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "How many players are on a baseball team on the field?",
    correct_answer: "9",
    incorrect_answers: ["11", "7", "10"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Which boxer was known as 'The Greatest'?",
    correct_answer: "Muhammad Ali",
    incorrect_answers: ["Mike Tyson", "Floyd Mayweather", "George Foreman"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "What object is hit in Badminton?",
    correct_answer: "Shuttlecock",
    incorrect_answers: ["Ball", "Puck", "Birdie"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "In golf, what is a score of one under par called?",
    correct_answer: "Birdie",
    incorrect_answers: ["Eagle", "Bogey", "Albatross"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Which country has won the most World Cups in soccer?",
    correct_answer: "Brazil",
    incorrect_answers: ["Germany", "Italy", "Argentina"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "Which sport takes place in a ring?",
    correct_answer: "Boxing",
    incorrect_answers: ["Tennis", "Swimming", "Golf"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "What is the maximum break in Snooker?",
    correct_answer: "147",
    incorrect_answers: ["155", "100", "180"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "Who is known as 'CR7'?",
    correct_answer: "Cristiano Ronaldo",
    incorrect_answers: ["Lionel Messi", "Ronaldinho", "Neymar"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "easy",
    question: "In which sport do you use a cue?",
    correct_answer: "Billiards/Pool",
    incorrect_answers: ["Golf", "Hockey", "Cricket"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "medium",
    question: "How many minutes is a rugby match?",
    correct_answer: "80",
    incorrect_answers: ["90", "60", "70"],
  },
  {
    category: 21,
    type: "multiple",
    difficulty: "hard",
    question: "Which year were the first modern Olympics held?",
    correct_answer: "1896",
    incorrect_answers: ["1900", "1924", "1888"],
  },
