export const CUSTOM_QUESTIONS_RO = [
{
  category: 9, // Cunostinte generale
  type: "multiple",
  difficulty: "easy",
  question: "Care este capitala Frantei?",
  correct_answer: "Paris",
  incorrect_answers: ["Londra", "Berlin", "Madrid"],
},
{
  category: 11, // Filme
  type: "multiple",
  difficulty: "medium",
  question: "Cine a regizat filmul 'Inception'?",
  correct_answer: "Christopher Nolan",
  incorrect_answers: ["Steven Spielberg", "Quentin Tarantino", "Martin Scorsese"],
},
// --- CUNOSTINTE GENERALE (BATCH 1) ---
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce animal este cunoscut ca 'Corabia desertului'?",
  correct_answer: "Camila",
  incorrect_answers: ["Cal", "Elefant", "Zebra"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cate zile are un an bisect?",
  correct_answer: "366",
  incorrect_answers: ["365", "364", "360"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste zeul grec al razboiului?",
  correct_answer: "Ares",
  incorrect_answers: ["Zeus", "Apollo", "Hermes"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce tara a oferit Statuia Libertatii Statelor Unite?",
  correct_answer: "Franta",
  incorrect_answers: ["Regatul Unit", "Spania", "Italia"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Care este cea mai rara grupa de sange?",
  correct_answer: "AB negativ",
  incorrect_answers: ["O pozitiv", "B negativ", "A pozitiv"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este cel mai mare ocean din lume?",
  correct_answer: "Oceanul Pacific",
  incorrect_answers: ["Oceanul Atlantic", "Oceanul Indian", "Oceanul Arctic"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce element chimic are simbolul 'K'?",
  correct_answer: "Potasiu",
  incorrect_answers: ["Kripton", "Keviniu", "Kalphon"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cine a pictat Mona Lisa?",
  correct_answer: "Leonardo da Vinci",
  incorrect_answers: ["Pablo Picasso", "Vincent van Gogh", "Michelangelo"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Care planeta are cei mai multi sateliti naturali?",
  correct_answer: "Saturn",
  incorrect_answers: ["Jupiter", "Uranus", "Neptun"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste frica de paianjeni?",
  correct_answer: "Arahnofobie",
  incorrect_answers: ["Acrofobie", "Claustrofobie", "Hidrofobie"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce fruct este asociat cu Isaac Newton?",
  correct_answer: "Mar",
  incorrect_answers: ["Para", "Portocala", "Banana"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce companie detine Bugatti, Lamborghini si Audi?",
  correct_answer: "Volkswagen",
  incorrect_answers: ["Toyota", "General Motors", "Ford"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este ingredientul principal din guacamole?",
  correct_answer: "Avocado",
  incorrect_answers: ["Rosie", "Ceapa", "Ardei"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cate inimi are o caracatita?",
  correct_answer: "3",
  incorrect_answers: ["1", "2", "4"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "In ce an a cazut Zidul Berlinului?",
  correct_answer: "1989",
  incorrect_answers: ["1987", "1991", "1990"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce inseamna prescurtarea 'www' intr-un browser web?",
  correct_answer: "World Wide Web",
  incorrect_answers: ["World Web Wide", "Wide World Web", "Web World Wide"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce fizician celebru a scris 'Scurta istorie a timpului'?",
  correct_answer: "Stephen Hawking",
  incorrect_answers: ["Albert Einstein", "Isaac Newton", "Niels Bohr"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Care este cel mai mic os din corpul uman?",
  correct_answer: "Scarita (osul urechii)",
  incorrect_answers: ["Falange", "Femur", "Tibia"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce litera urmeaza dupa 'F' in alfabet?",
  correct_answer: "G",
  incorrect_answers: ["E", "H", "I"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este cea mai dura substanta naturala de pe Pamant?",
  correct_answer: "Diamant",
  incorrect_answers: ["Aur", "Fier", "Platina"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce personaj Disney este un elefant zburator?",
  correct_answer: "Dumbo",
  incorrect_answers: ["Bambi", "Simba", "Pluto"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce oras este cunoscut sub numele de 'Marele Mar'?",
  correct_answer: "New York",
  incorrect_answers: ["Los Angeles", "Chicago", "Miami"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Ce element are numarul atomic 1?",
  correct_answer: "Hidrogen",
  incorrect_answers: ["Heliu", "Oxigen", "Carbon"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce culoare are un safir?",
  correct_answer: "Albastru",
  incorrect_answers: ["Rosu", "Verde", "Galben"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce tara a inventat pizza?",
  correct_answer: "Italia",
  incorrect_answers: ["SUA", "Franta", "China"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "In ce an a pasit primul om pe Luna?",
  correct_answer: "1969",
  incorrect_answers: ["1965", "1972", "1959"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cate picioare are un paianjen?",
  correct_answer: "8",
  incorrect_answers: ["6", "4", "10"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este floarea nationala a Japoniei?",
  correct_answer: "Floarea de cires",
  incorrect_answers: ["Trandafir", "Crin", "Lalea"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a scris romanul '1984'?",
  correct_answer: "George Orwell",
  incorrect_answers: ["Aldous Huxley", "Ernest Hemingway", "F. Scott Fitzgerald"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste forma inghetata a apei?",
  correct_answer: "Gheata",
  incorrect_answers: ["Abur", "Lichid", "Gaz"],
},
// --- CUNOSTINTE GENERALE (BATCH 2 - EXTINS) ---
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce limba are cei mai multi vorbitori nativi din lume?",
  correct_answer: "Mandarina",
  incorrect_answers: ["Engleza", "Spaniola", "Hindi"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este culoarea principala a logo-ului Netflix?",
  correct_answer: "Rosu",
  incorrect_answers: ["Albastru", "Verde", "Negru"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a fost prima femeie care a castigat un premiu Nobel?",
  correct_answer: "Marie Curie",
  incorrect_answers: ["Maica Tereza", "Jane Addams", "Rosalind Franklin"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce brand foloseste sloganul 'Just Do It'?",
  correct_answer: "Nike",
  incorrect_answers: ["Adidas", "Puma", "Reebok"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce pasare este cunoscuta pentru imitarea vocii umane?",
  correct_answer: "Papagal",
  incorrect_answers: ["Vultur", "Bufnita", "Pinguin"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este cel mai inalt mamifer din lume?",
  correct_answer: "Girafa",
  incorrect_answers: ["Elefant", "Balena albastra", "Cal"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Ce piesa de sah se poate misca doar pe diagonala?",
  correct_answer: "Nebun",
  incorrect_answers: ["Tura", "Cal", "Pion"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cate laturi are un triunghi?",
  correct_answer: "3",
  incorrect_answers: ["4", "5", "2"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este cea mai fierbinte planeta din sistemul nostru solar?",
  correct_answer: "Venus",
  incorrect_answers: ["Mercur", "Marte", "Jupiter"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste jucaria cowboy din 'Toy Story'?",
  correct_answer: "Woody",
  incorrect_answers: ["Buzz", "Andy", "Jessie"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "In ce an a aparut filmul Titanic?",
  correct_answer: "1997",
  incorrect_answers: ["1995", "1999", "2000"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce tara produce cea mai multa cafea din lume?",
  correct_answer: "Brazilia",
  incorrect_answers: ["Columbia", "Vietnam", "Etiopia"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este opusul cuvantului 'cald'?",
  correct_answer: "Rece",
  incorrect_answers: ["Caldut", "Tepos", "Picant"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a fondat Microsoft?",
  correct_answer: "Bill Gates",
  incorrect_answers: ["Steve Jobs", "Elon Musk", "Mark Zuckerberg"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este moneda Regatului Unit?",
  correct_answer: "Lira sterlina",
  incorrect_answers: ["Euro", "Dolar", "Yen"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce animal este simbolul WWF?",
  correct_answer: "Panda",
  incorrect_answers: ["Tigru", "Leu", "Urs"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cate stele sunt pe steagul Chinei?",
  correct_answer: "5",
  incorrect_answers: ["4", "6", "1"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce organ pompeaza sangele in corpul uman?",
  correct_answer: "Inima",
  incorrect_answers: ["Creierul", "Plamanii", "Ficatul"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este culoarea principala a unei banane?",
  correct_answer: "Galben",
  incorrect_answers: ["Rosu", "Verde", "Albastru"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce vas celebru s-a scufundat in 1912?",
  correct_answer: "Titanic",
  incorrect_answers: ["Lusitania", "Olympic", "Britannic"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Ce gaz reprezinta cea mai mare parte din atmosfera Pamantului?",
  correct_answer: "Azot",
  incorrect_answers: ["Oxigen", "Dioxid de carbon", "Hidrogen"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce produc albinele?",
  correct_answer: "Miere",
  incorrect_answers: ["Lapte", "Matase", "Lana"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Cine este autorul seriei 'Harry Potter'?",
  correct_answer: "J.K. Rowling",
  incorrect_answers: ["J.R.R. Tolkien", "George R.R. Martin", "Stephen King"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Ce reprezinta litera 'O' in codul Morse?",
  correct_answer: "---",
  incorrect_answers: ["...", ".-", "-.-"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce tara are cea mai mare populatie?",
  correct_answer: "India",
  incorrect_answers: ["China", "SUA", "Rusia"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce anotimp urmeaza dupa vara?",
  correct_answer: "Toamna",
  incorrect_answers: ["Iarna", "Primavara", "Muson"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce inseamna litera 'E' din 'Email'?",
  correct_answer: "Electronic",
  incorrect_answers: ["Electric", "Motor", "Usor"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Ce artist si-a taiat propria ureche?",
  correct_answer: "Vincent van Gogh",
  incorrect_answers: ["Pablo Picasso", "Claude Monet", "Salvador Dali"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este cel mai rapid animal de uscat?",
  correct_answer: "Ghepard",
  incorrect_answers: ["Leu", "Cal", "Tigru"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Cati jucatori sunt intr-o echipa standard de fotbal?",
  correct_answer: "11",
  incorrect_answers: ["10", "12", "9"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Care este capitala Canadei?",
  correct_answer: "Ottawa",
  incorrect_answers: ["Toronto", "Montreal", "Vancouver"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce personaj din basme a dormit 100 de ani?",
  correct_answer: "Frumoasa din padurea adormita",
  incorrect_answers: ["Cenusareasa", "Alba ca Zapada", "Rapunzel"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce producator auto are un cal in logo?",
  correct_answer: "Ferrari",
  incorrect_answers: ["Lamborghini", "Audi", "BMW"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a fost primul om care a pasit pe Luna?",
  correct_answer: "Neil Armstrong",
  incorrect_answers: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este cel mai mare organ intern din corpul uman?",
  correct_answer: "Ficatul",
  incorrect_answers: ["Inima", "Plamanii", "Stomacul"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Ce fel de mancare este Penne?",
  correct_answer: "Paste",
  incorrect_answers: ["Paine", "Branza", "Carne"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce tara este faimoasa pentru lalele si mori de vant?",
  correct_answer: "Olanda",
  incorrect_answers: ["Germania", "Elvetia", "Belgia"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Care este simbolul chimic pentru aur?",
  correct_answer: "Au",
  incorrect_answers: ["Ag", "Go", "Gd"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Cate ore are o zi?",
  correct_answer: "24",
  incorrect_answers: ["12", "48", "36"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Cine a pictat tavanul Capelei Sixtine?",
  correct_answer: "Michelangelo",
  incorrect_answers: ["Leonardo da Vinci", "Raphael", "Donatello"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Ce razboi a fost purtat intre regiunile de Nord si Sud ale Statelor Unite?",
  correct_answer: "Razboiul Civil",
  incorrect_answers: ["Razboiul de Independenta", "Primul Razboi Mondial", "Razboiul din Vietnam"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este cea mai mare reptila vie?",
  correct_answer: "Crocodilul de apa sarata",
  incorrect_answers: ["Dragonul de Komodo", "Pitonu", "Aligatorul"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste orasul fictiv in care locuieste Batman?",
  correct_answer: "Gotham City",
  incorrect_answers: ["Metropolis", "Star City", "Central City"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "hard",
  question: "Cate dungi sunt pe steagul SUA?",
  correct_answer: "13",
  incorrect_answers: ["50", "10", "12"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Ce bautura racoritoare a fost initial verde?",
  correct_answer: "Niciuna (este un mit, dar este asociat des cu Mountain Dew)",
  incorrect_answers: ["Coca Cola", "Pepsi", "Sprite"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "medium",
  question: "Care este cea mai dura roca?",
  correct_answer: "Diamant",
  incorrect_answers: ["Granit", "Marmura", "Cuart"],
},
{
  category: 9,
  type: "multiple",
  difficulty: "easy",
  question: "Care este ingredientul principal din ciocolata?",
  correct_answer: "Cacao",
  incorrect_answers: ["Lapte", "Zahar", "Vanilie"],
},
// --- FILME (BATCH 1 - MIX) ---
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In ce film apare un personaj numit Jack Sparrow?",
  correct_answer: "Pirates of the Caribbean",
  incorrect_answers: ["Harry Potter", "Lord of the Rings", "Indiana Jones"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In 'The Matrix', ce pastila ia Neo?",
  correct_answer: "Rosie",
  incorrect_answers: ["Albastra", "Verde", "Galbena"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cine l-a interpretat pe Iron Man in universul cinematografic Marvel?",
  correct_answer: "Robert Downey Jr.",
  incorrect_answers: ["Chris Evans", "Chris Hemsworth", "Mark Ruffalo"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Ce film a castigat Oscarul pentru Cel mai bun film in 1994?",
  correct_answer: "Schindler's List",
  incorrect_answers: ["Pulp Fiction", "Forrest Gump", "The Shawshank Redemption"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste regatul din 'Frozen'?",
  correct_answer: "Arendelle",
  incorrect_answers: ["Genovia", "Aldovia", "Florin"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce dinozaur este antagonistul principal in 'Jurassic Park'?",
  correct_answer: "T-Rex",
  incorrect_answers: ["Velociraptor", "Triceratops", "Brachiosaurus"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cine a regizat filmul 'Avatar'?",
  correct_answer: "James Cameron",
  incorrect_answers: ["Steven Spielberg", "George Lucas", "Ridley Scott"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "In 'Pulp Fiction', cum se numeste un 'Quarter Pounder with Cheese' in Paris?",
  correct_answer: "Royale with Cheese",
  incorrect_answers: ["Le Big Mac", "French Burger", "Cheese Royale"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce fel de animal este Baloo in 'The Jungle Book'?",
  correct_answer: "Urs",
  incorrect_answers: ["Tigru", "Lup", "Pantera"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce actor a jucat Joker-ul in 'The Dark Knight'?",
  correct_answer: "Heath Ledger",
  incorrect_answers: ["Joaquin Phoenix", "Jared Leto", "Jack Nicholson"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cine locuieste intr-un ananas sub mare?",
  correct_answer: "SpongeBob SquarePants",
  incorrect_answers: ["Patrick Star", "Squidward", "Mr. Krabs"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cum se numeste computerul din '2001: A Space Odyssey'?",
  correct_answer: "HAL 9000",
  incorrect_answers: ["Skynet", "Jarvis", "Deep Blue"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Din ce film este citatul 'Here's looking at you, kid'?",
  correct_answer: "Casablanca",
  incorrect_answers: ["Gone with the Wind", "Citizen Kane", "The Godfather"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In 'Harry Potter', cum se numeste bufnita lui Harry?",
  correct_answer: "Hedwig",
  incorrect_answers: ["Scabbers", "Crookshanks", "Fang"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cine a jucat rolul lui Jack Dawson in 'Titanic'?",
  correct_answer: "Leonardo DiCaprio",
  incorrect_answers: ["Brad Pitt", "Matt Damon", "Johnny Depp"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Care a fost primul film lansat in Marvel Cinematic Universe?",
  correct_answer: "Iron Man",
  incorrect_answers: ["The Incredible Hulk", "Captain America", "Thor"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste capcaunul din 'Shrek'?",
  correct_answer: "Shrek",
  incorrect_answers: ["Donkey", "Fiona", "Farquaad"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In 'Star Wars', cine este tatal lui Luke Skywalker?",
  correct_answer: "Darth Vader",
  incorrect_answers: ["Obi-Wan Kenobi", "Palpatine", "Yoda"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Ce film este plasat in tara fictiva Wakanda?",
  correct_answer: "Black Panther",
  incorrect_answers: ["Coming to America", "District 9", "Hotel Rwanda"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce supererou este cunoscut ca 'Omul de otel'?",
  correct_answer: "Superman",
  incorrect_answers: ["Batman", "Iron Man", "Thor"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce actor si-a facut faimoase cascadoriile singur in 'Mission: Impossible'?",
  correct_answer: "Tom Cruise",
  incorrect_answers: ["Keanu Reeves", "Daniel Craig", "Jason Statham"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cum se numeste sania din 'Citizen Kane'?",
  correct_answer: "Rosebud",
  incorrect_answers: ["Snowbird", "Thunder", "Lightning"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In 'Finding Nemo', ce fel de peste este Nemo?",
  correct_answer: "Peste clovn",
  incorrect_answers: ["Peste auriu", "Rechin", "Peste balon"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce film are un parc tematic cu dinozauri clonati?",
  correct_answer: "Jurassic Park",
  incorrect_answers: ["King Kong", "Godzilla", "Planet of the Apes"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'Psycho'?",
  correct_answer: "Alfred Hitchcock",
  incorrect_answers: ["Stanley Kubrick", "Francis Ford Coppola", "Martin Scorsese"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce personaj spune 'I am Groot'?",
  correct_answer: "Groot",
  incorrect_answers: ["Rocket", "Star-Lord", "Drax"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce culoare are sabia laser a lui Mace Windu in 'Star Wars'?",
  correct_answer: "Mov",
  incorrect_answers: ["Verde", "Albastru", "Rosu"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "In ce film apare melodia 'My Heart Will Go On'?",
  correct_answer: "Titanic",
  incorrect_answers: ["The Bodyguard", "Ghost", "Pretty Woman"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste majordomul loial al lui Batman?",
  correct_answer: "Alfred",
  incorrect_answers: ["Robin", "Gordon", "Lucius"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce film spune povestea lui Mozart?",
  correct_answer: "Amadeus",
  incorrect_answers: ["Immortal Beloved", "Shine", "The Pianist"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Care este filmul cu cele mai mari incasari din toate timpurile (pana in 2023)?",
  correct_answer: "Avatar",
  incorrect_answers: ["Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce printesa Disney are un pantof de sticla?",
  correct_answer: "Cenusareasa",
  incorrect_answers: ["Snow White", "Belle", "Aurora"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cine a jucat rolul lui Forrest Gump?",
  correct_answer: "Tom Hanks",
  incorrect_answers: ["Harrison Ford", "Bill Murray", "Kevin Costner"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "In 'The Silence of the Lambs', cum se numeste criminalul in serie?",
  correct_answer: "Hannibal Lecter",
  incorrect_answers: ["Norman Bates", "Jack Torrance", "Patrick Bateman"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce oras fictiv este casa lui Superman?",
  correct_answer: "Metropolis",
  incorrect_answers: ["Gotham", "Star City", "Smallville"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce film are o masina DeLorean care calatoreste in timp?",
  correct_answer: "Back to the Future",
  incorrect_answers: ["Blade Runner", "Total Recall", "The Terminator"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'The Godfather'?",
  correct_answer: "Francis Ford Coppola",
  incorrect_answers: ["Martin Scorsese", "Sergio Leone", "Brian De Palma"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce animal este Simba in 'The Lion King'?",
  correct_answer: "Leu",
  incorrect_answers: ["Tigru", "Ghepard", "Leopard"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In ce film apare o minge de volei numita Wilson?",
  correct_answer: "Cast Away",
  incorrect_answers: ["The Terminal", "Apollo 13", "Saving Private Ryan"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cum se numeste hotelul din 'The Shining'?",
  correct_answer: "Overlook Hotel",
  incorrect_answers: ["Bates Motel", "Grand Budapest Hotel", "Hotel California"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cine este personajul negativ din '101 Dalmatians'?",
  correct_answer: "Cruella de Vil",
  incorrect_answers: ["Ursula", "Maleficent", "Evil Queen"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce actrita a jucat-o pe Katniss Everdeen in 'The Hunger Games'?",
  correct_answer: "Jennifer Lawrence",
  incorrect_answers: ["Emma Watson", "Shailene Woodley", "Kristen Stewart"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Ce film a castigat primul Oscar din istorie pentru Cel mai bun film?",
  correct_answer: "Wings",
  incorrect_answers: ["Sunrise", "Metropolis", "The Jazz Singer"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce jucarii prind viata in 'Toy Story'?",
  correct_answer: "Toate",
  incorrect_answers: ["Doar Woody", "Doar Buzz", "Niciuna"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Din ce film este replica 'You can't handle the truth!'?",
  correct_answer: "A Few Good Men",
  incorrect_answers: ["Top Gun", "Jerry Maguire", "Rain Man"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Care este numele real al lui The Rock?",
  correct_answer: "Dwayne Johnson",
  incorrect_answers: ["Steve Austin", "John Cena", "Dave Bautista"],
},
// --- FILME (BATCH 2 - EXTINS) ---
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste cainele din 'The Wizard of Oz'?",
  correct_answer: "Toto",
  incorrect_answers: ["Lassie", "Buddy", "Rex"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In 'Fight Club', care este prima regula a Fight Club?",
  correct_answer: "Nu vorbesti despre Fight Club",
  incorrect_answers: ["Nu te bati fara tricou", "Doi baieti la o lupta", "Luptele continua cat este nevoie"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Ce film a castigat Oscarul pentru Cel mai bun film in 2020 (primul film intr-o limba non-engleza care a castigat)?",
  correct_answer: "Parasite",
  incorrect_answers: ["Roma", "1917", "Jojo Rabbit"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce actor il joaca pe Wolverine in filmele X-Men?",
  correct_answer: "Hugh Jackman",
  incorrect_answers: ["Christian Bale", "Tom Hardy", "Ben Affleck"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste insula din 'Jurassic Park'?",
  correct_answer: "Isla Nublar",
  incorrect_answers: ["Isla Sorna", "Isla Mujeres", "Isla Grande"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'E.T. the Extra-Terrestrial'?",
  correct_answer: "Steven Spielberg",
  incorrect_answers: ["George Lucas", "James Cameron", "Tim Burton"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste omul de zapada din 'Frozen'?",
  correct_answer: "Olaf",
  incorrect_answers: ["Sven", "Kristoff", "Hans"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce film il are ca personaj pe 'Donnie Darko'?",
  correct_answer: "Donnie Darko",
  incorrect_answers: ["Nightcrawler", "Prisoners", "Zodiac"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "In 'The Matrix', cum se numeste nava condusa de Morpheus?",
  correct_answer: "Nebuchadnezzar",
  incorrect_answers: ["Icarus", "Prometheus", "Nostromo"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cine este principalul antagonist in 'Star Wars: A New Hope'?",
  correct_answer: "Darth Vader",
  incorrect_answers: ["Emperor Palpatine", "Kylo Ren", "Darth Maul"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Din ce film este replica 'I see dead people'?",
  correct_answer: "The Sixth Sense",
  incorrect_answers: ["The Others", "Poltergeist", "Ghostbusters"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cum se numeste demonul din 'The Exorcist'?",
  correct_answer: "Pazuzu",
  incorrect_answers: ["Beelzebub", "Azazel", "Lucifer"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce supererou este Peter Parker?",
  correct_answer: "Spider-Man",
  incorrect_answers: ["Superman", "Batman", "Flash"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cine l-a jucat pe Neo in 'The Matrix'?",
  correct_answer: "Keanu Reeves",
  incorrect_answers: ["Will Smith", "Brad Pitt", "Tom Cruise"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Ce film este bazat pe un roman de Stephen King despre un clovn?",
  correct_answer: "It",
  incorrect_answers: ["The Shining", "Carrie", "Misery"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste leul din 'The Chronicles of Narnia'?",
  correct_answer: "Aslan",
  incorrect_answers: ["Simba", "Mufasa", "Scar"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In ce film apare un personaj numit 'The Dude'?",
  correct_answer: "The Big Lebowski",
  incorrect_answers: ["Fargo", "No Country for Old Men", "Burn After Reading"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'Blade Runner' (1982)?",
  correct_answer: "Ridley Scott",
  incorrect_answers: ["Denis Villeneuve", "James Cameron", "George Miller"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce film este despre un parc tematic cu dinozauri?",
  correct_answer: "Jurassic Park",
  incorrect_answers: ["King Kong", "Godzilla", "The Land Before Time"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste inelul din 'The Lord of the Rings'?",
  correct_answer: "The One Ring",
  incorrect_answers: ["The Ring of Power", "The Precious Ring", "The Golden Ring"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "In 'Goodfellas', cum se numeste personajul jucat de Ray Liotta?",
  correct_answer: "Henry Hill",
  incorrect_answers: ["Tommy DeVito", "Jimmy Conway", "Paul Cicero"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In ce film apare un personaj numit 'Buzz Lightyear'?",
  correct_answer: "Toy Story",
  incorrect_answers: ["Cars", "Monsters, Inc.", "The Incredibles"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cine a jucat Joker-ul in filmul 'Batman' din 1989?",
  correct_answer: "Jack Nicholson",
  incorrect_answers: ["Heath Ledger", "Jared Leto", "Cesar Romero"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Din ce film este replica 'You talking to me?'?",
  correct_answer: "Taxi Driver",
  incorrect_answers: ["Raging Bull", "Goodfellas", "Mean Streets"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cum se numeste zana din 'Peter Pan'?",
  correct_answer: "Tinker Bell",
  incorrect_answers: ["Silvermist", "Fawn", "Iridessa"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Ce film este plasat pe planeta Pandora?",
  correct_answer: "Avatar",
  incorrect_answers: ["Star Trek", "Guardians of the Galaxy", "Alien"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'Inception'?",
  correct_answer: "Christopher Nolan",
  incorrect_answers: ["Quentin Tarantino", "David Fincher", "Wes Anderson"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce film are un personaj numit 'Shrek'?",
  correct_answer: "Shrek",
  incorrect_answers: ["Ice Age", "Madagascar", "Kung Fu Panda"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste hotelul din 'Pretty Woman'?",
  correct_answer: "Regent Beverly Wilshire",
  incorrect_answers: ["The Plaza", "The Ritz", "The Waldorf Astoria"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Ce film a castigat Oscarul pentru Cel mai bun film in 2017 (dupa o incurcatura)?",
  correct_answer: "Moonlight",
  incorrect_answers: ["La La Land", "Arrival", "Manchester by the Sea"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Cine este personajul principal din 'The Lion King'?",
  correct_answer: "Simba",
  incorrect_answers: ["Mufasa", "Nala", "Scar"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In ce film apare melodia 'Eye of the Tiger'?",
  correct_answer: "Rocky III",
  incorrect_answers: ["The Karate Kid", "Top Gun", "Flashdance"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine l-a jucat pe Hannibal Lecter in 'The Silence of the Lambs'?",
  correct_answer: "Anthony Hopkins",
  incorrect_answers: ["Brian Cox", "Mads Mikkelsen", "Jeremy Irons"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In ce film apare un personaj numit 'Dory'?",
  correct_answer: "Finding Nemo",
  incorrect_answers: ["The Little Mermaid", "Shark Tale", "Moana"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Cum se numeste nava spatiala din 'Alien'?",
  correct_answer: "Nostromo",
  incorrect_answers: ["Sulaco", "Prometheus", "Covenant"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'The Grand Budapest Hotel'?",
  correct_answer: "Wes Anderson",
  incorrect_answers: ["Paul Thomas Anderson", "Coen Brothers", "Spike Jonze"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In ce film apare un personaj numit 'Elsa'?",
  correct_answer: "Frozen",
  incorrect_answers: ["Tangled", "Brave", "Moana"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "Din ce film este citatul 'Frankly, my dear, I don't give a damn'?",
  correct_answer: "Gone with the Wind",
  incorrect_answers: ["Casablanca", "Citizen Kane", "The Wizard of Oz"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine l-a jucat pe Tyler Durden in 'Fight Club'?",
  correct_answer: "Brad Pitt",
  incorrect_answers: ["Edward Norton", "Jared Leto", "Matt Damon"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "In ce film apare un personaj numit 'Lightning McQueen'?",
  correct_answer: "Cars",
  incorrect_answers: ["Planes", "Turbo", "Herbie"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "medium",
  question: "In ce film apare melodia 'Unchained Melody'?",
  correct_answer: "Ghost",
  incorrect_answers: ["Dirty Dancing", "Pretty Woman", "Top Gun"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "hard",
  question: "Cine a regizat 'Schindler's List'?",
  correct_answer: "Steven Spielberg",
  incorrect_answers: ["Roman Polanski", "Martin Scorsese", "Francis Ford Coppola"],
},
{
  category: 11,
  type: "multiple",
  difficulty: "easy",
  question: "Ce film are un personaj numit 'Gru'?",
  correct_answer: "Despicable Me",
  incorrect_answers: ["Megamind", "The Incredibles", "Minions"],
},
  {
    category: 11,
    type: "multiple",
    difficulty: "medium",
    question: "In ce film apare replica 'Hasta la vista, baby'?",
    correct_answer: "Terminator 2: Judgment Day",
    incorrect_answers: ["Total Recall", "Predator", "Commando"],
  },
  {
    category: 11,
    type: "multiple",
    difficulty: "hard",
    question: "Cine a jucat rolul personajului Jack Torrance in 'The Shining'?",
    correct_answer: "Jack Nicholson",
    incorrect_answers: ["Robert De Niro", "Al Pacino", "Dustin Hoffman"],
  },
